## Introduction
*Pending*

In [83]:
import pandas as pd
from pathlib import Path

## Phase 1: Initial Reconnaisance
Seeks to answer the following questions:
- Tidy or not?
- What are the entities, attributes (cols), observations (rows)?
- What variable types do I have?
- What's the rough shape and scale?
- Are there obvious problems?

In [84]:
#load arrivals datset
arrivals_path = Path("../data/Raw/Arrivals_AA_DFW_2016_2025.csv")
arrivals = pd.read_csv(arrivals_path, skiprows=7)

arrivals.head()
departures.tail()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
1382457,AA,12/31/2024,3211.0,N870NN,CMH,14:59,14:54,146.0,132.0,-5.0,15:12,18.0,0.0,0.0,0.0,0.0,0.0
1382458,AA,12/31/2024,3221.0,N8001N,LIT,17:55,18:51,73.0,61.0,56.0,19:07,16.0,8.0,0.0,0.0,0.0,36.0
1382459,AA,12/31/2024,3222.0,N104UW,OKC,19:45,19:39,63.0,54.0,-6.0,19:55,16.0,0.0,0.0,0.0,0.0,0.0
1382460,AA,12/31/2024,3224.0,N662AW,SAV,19:30,19:41,136.0,126.0,11.0,19:58,17.0,0.0,0.0,0.0,0.0,0.0
1382461,AA,12/31/2024,3239.0,N822NN,AMA,16:36,16:36,76.0,74.0,0.0,16:51,15.0,0.0,0.0,0.0,0.0,0.0

In [85]:
#load departures datset
departures_path = Path("../data/Raw/Departures_AA_DFW_2016_2025.csv")
departures = pd.read_csv(departures_path, skiprows=7)

departures.head()
departures.tail()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
1382465,AA,12/31/2024,3267.0,N744P,BHM,14:55,14:48,103.0,92.0,-7.0,15:03,15.0,0.0,0.0,0.0,0.0,0.0
1382466,AA,12/31/2024,3279.0,N711UW,ELP,12:26,12:23,118.0,105.0,-3.0,12:38,15.0,0.0,0.0,0.0,0.0,0.0
1382467,AA,12/31/2024,3287.0,N994NN,BOS,07:05,07:06,217.0,207.0,1.0,07:28,22.0,0.0,0.0,0.0,0.0,0.0
1382468,AA,12/31/2024,3295.0,N198UW,LAX,13:15,13:16,204.0,209.0,1.0,13:31,15.0,0.0,0.0,0.0,0.0,0.0
1382469,SOURCE: Bureau of Transportation Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
columns_df = pd.DataFrame({
    "departures": sorted(departures.columns),
    "arrivals": sorted(arrivals.columns)
        })
columns_df

,departures,arrivals
0,Actual departure time,Actual Arrival Time
1,Actual elapsed time (Minutes),Actual Elapsed Time (Minutes)
2,Carrier Code,Arrival Delay (Minutes)
3,Date (MM/DD/YYYY),Carrier Code
4,Delay Carrier (Minutes),Date (MM/DD/YYYY)
5,Delay Late Aircraft Arrival (Minutes),Delay Carrier (Minutes)
6,Delay National Aviation System (Minutes),Delay Late Aircraft Arrival (Minutes)
7,Delay Security (Minutes),Delay National Aviation System (Minutes)
8,Delay Weather (Minutes),Delay Security (Minutes)
9,Departure delay (Minutes),Delay Weather (Minutes)
10,Destination Airport,Flight Number
11,Flight Number,Origin Airport
12,Scheduled departure time,Scheduled Arrival Time
13,Scheduled elapsed time (Minutes),Scheduled Elapsed Time (Minutes)
14,Tail Number,Tail Number
15,Taxi-Out time (Minutes),Taxi-In time (Minutes)
16,Wheels-off time,Wheels-on Time

In [87]:
# Departures Summaries
print("="*20, "Info", "="*20)
print(departures.info())
print("="*20, "Unique Observations","="*20)
print(departures.nunique())
print("="*20, "Shape","="*20)
print(departures.shape)

==================== Info ====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382470 entries, 0 to 1382469
Data columns (total 17 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Carrier Code                              1382470 non-null  object
 1   Date (MM/DD/YYYY)                         1382469 non-null  object
 2   Flight Number                             1382469 non-null  float64
 3   Tail Number                               1380181 non-null  object
 4   Destination Airport                       1382469 non-null  object
 5   Scheduled departure time                  1382469 non-null  object
 6   Actual departure time                     1382469 non-null  object
 7   Scheduled elapsed time (Minutes)          1382469 non-null  float64
 8   Actual elapsed time (Minutes)             1382469 non-null  float64
 9   Departure delay (Minutes)                 1382469 non-null  float64
 10  Wheels-off time                           1382469 non-null  object
 11  Taxi-Out time (Minutes)                   1382469 non-null  float64
 12  Delay Carrier (Minutes)                   1382469 non-null  float64
 13  Delay Weather (Minutes)                   1382469 non-null  float64
 14  Delay National Aviation System (Minutes)  1382469 non-null  float64
 15  Delay Security (Minutes)                  1382469 non-null  float64
 16  Delay Late Aircraft Arrival (Minutes)     1382469 non-null  float64
dtypes: float64(10), object(7)
memory usage: 179.3+ MB
None
==================== Unique Observations ====================
Carrier Code                                   2
Date (MM/DD/YYYY)                           3500
Flight Number                               2924
Tail Number                                 2064
Destination Airport                          136
Scheduled departure time                    1152
Actual departure time                       1376
Scheduled elapsed time (Minutes)             354
Actual elapsed time (Minutes)                565
Departure delay (Minutes)                   1186
Wheels-off time                             1382
Taxi-Out time (Minutes)                      177
Delay Carrier (Minutes)                      854
Delay Weather (Minutes)                      596
Delay National Aviation System (Minutes)     345
Delay Security (Minutes)                     109
Delay Late Aircraft Arrival (Minutes)        928
dtype: int64
==================== Shape ====================
(1382470, 17)

In [88]:
# Arrivals Summaries
print("="*20, "Info", "="*20)
print(arrivals.info())
print("="*20, "Unique Observations","="*20)
print(arrivals.nunique())
print("="*20, "Shape","="*20)
print(arrivals.shape)

==================== Info ====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382406 entries, 0 to 1382405
Data columns (total 17 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Carrier Code                              1382406 non-null  object
 1   Date (MM/DD/YYYY)                         1382405 non-null  object
 2   Flight Number                             1382405 non-null  float64
 3   Tail Number                               1380193 non-null  object
 4   Origin Airport                            1382405 non-null  object
 5   Scheduled Arrival Time                    1382405 non-null  object
 6   Actual Arrival Time                       1382405 non-null  object
 7   Scheduled Elapsed Time (Minutes)          1382405 non-null  float64
 8   Actual Elapsed Time (Minutes)             1382405 non-null  float64
 9   Arrival Delay (Minutes)                   1382405 non-null  float64
 10  Wheels-on Time                            1382405 non-null  object
 11  Taxi-In time (Minutes)                    1382405 non-null  float64
 12  Delay Carrier (Minutes)                   1382405 non-null  float64
 13  Delay Weather (Minutes)                   1382405 non-null  float64
 14  Delay National Aviation System (Minutes)  1382405 non-null  float64
 15  Delay Security (Minutes)                  1382405 non-null  float64
 16  Delay Late Aircraft Arrival (Minutes)     1382405 non-null  float64
dtypes: float64(10), object(7)
memory usage: 179.3+ MB
None
==================== Unique Observations ====================
Carrier Code                                   2
Date (MM/DD/YYYY)                           3500
Flight Number                               2936
Tail Number                                 2063
Origin Airport                               136
Scheduled Arrival Time                      1309
Actual Arrival Time                         1441
Scheduled Elapsed Time (Minutes)             375
Actual Elapsed Time (Minutes)                476
Arrival Delay (Minutes)                     1891
Wheels-on Time                              1441
Taxi-In time (Minutes)                       211
Delay Carrier (Minutes)                     1647
Delay Weather (Minutes)                      624
Delay National Aviation System (Minutes)     502
Delay Security (Minutes)                     129
Delay Late Aircraft Arrival (Minutes)       1171
dtype: int64
==================== Shape ====================
(1382406, 17)

### Data Recon Assessment 
#### Tidiness
This dataset is tidy. Each variable forms one column, and each observation forms one row. We can further compress the columns by combining dates with time-of-day columns

#### Data Structure
Both the arrivals and departures datasets have 16 features. There are differing features between the two, specific to whether the plane is arriving or departing.  The datsets can be concantenated, and the various type-specific columns (e.g., the scheduled arrival/departure time columns) can be combined into a single column (e.g. "Scheduled Time").

There are over 1.3 million observations in each dataset.  

**Note: It's evident from looking at the tail of the datasets, that the final row can be dropped.**

In [89]:
arrivals = arrivals.iloc[:-1]
departures = departures.iloc[:-1]

print(arrivals.iloc[-1].isna().sum())
print(departures.iloc[-1].isna().sum())

0
0

## Phase 2: Data Quality Assessment
- Seeking to answer the following questions:
- Are types correct for each variable?
- Do values make domain sense?
- Where is data missing, and how much?
- Are there duplicates? Outliers?
- Can I trust this data as-is?

In [90]:
# Missing Values
print("="*20, "Arrivals Missing Values", "="*20)
print(arrivals.isna().sum())
print("="*20, "Departures Missing Values", "="*20)
print(departures.isna().sum())

==================== Arrivals Missing Values ====================
Carrier Code                                   0
Date (MM/DD/YYYY)                              0
Flight Number                                  0
Tail Number                                 2212
Origin Airport                                 0
Scheduled Arrival Time                         0
Actual Arrival Time                            0
Scheduled Elapsed Time (Minutes)               0
Actual Elapsed Time (Minutes)                  0
Arrival Delay (Minutes)                        0
Wheels-on Time                                 0
Taxi-In time (Minutes)                         0
Delay Carrier (Minutes)                        0
Delay Weather (Minutes)                        0
Delay National Aviation System (Minutes)       0
Delay Security (Minutes)                       0
Delay Late Aircraft Arrival (Minutes)          0
dtype: int64
==================== Departures Missing Values ====================
Carrier Code                                   0
Date (MM/DD/YYYY)                              0
Flight Number                                  0
Tail Number                                 2288
Destination Airport                            0
Scheduled departure time                       0
Actual departure time                          0
Scheduled elapsed time (Minutes)               0
Actual elapsed time (Minutes)                  0
Departure delay (Minutes)                      0
Wheels-off time                                0
Taxi-Out time (Minutes)                        0
Delay Carrier (Minutes)                        0
Delay Weather (Minutes)                        0
Delay National Aviation System (Minutes)       0
Delay Security (Minutes)                       0
Delay Late Aircraft Arrival (Minutes)          0
dtype: int64

In [91]:
# Data Types
print("="*20,"Arrivals:","="*20)
print(arrivals.dtypes)
print("="*20,"Departures:","="*20)
print(departures.dtypes)

==================== Arrivals: ====================
Carrier Code                                 object
Date (MM/DD/YYYY)                            object
Flight Number                               float64
Tail Number                                  object
Origin Airport                               object
Scheduled Arrival Time                       object
Actual Arrival Time                          object
Scheduled Elapsed Time (Minutes)            float64
Actual Elapsed Time (Minutes)               float64
Arrival Delay (Minutes)                     float64
Wheels-on Time                               object
Taxi-In time (Minutes)                      float64
Delay Carrier (Minutes)                     float64
Delay Weather (Minutes)                     float64
Delay National Aviation System (Minutes)    float64
Delay Security (Minutes)                    float64
Delay Late Aircraft Arrival (Minutes)       float64
dtype: object
==================== Departures: ====================
Carrier Code                                 object
Date (MM/DD/YYYY)                            object
Flight Number                               float64
Tail Number                                  object
Destination Airport                          object
Scheduled departure time                     object
Actual departure time                        object
Scheduled elapsed time (Minutes)            float64
Actual elapsed time (Minutes)               float64
Departure delay (Minutes)                   float64
Wheels-off time                              object
Taxi-Out time (Minutes)                     float64
Delay Carrier (Minutes)                     float64
Delay Weather (Minutes)                     float64
Delay National Aviation System (Minutes)    float64
Delay Security (Minutes)                    float64
Delay Late Aircraft Arrival (Minutes)       float64
dtype: object

### Validation

In [92]:
#Validate time-of-day fields by converting to datetime objects, coercing errors to generate NaN's
def invalid_times(tcol):
    converted = pd.to_datetime(tcol, format="%H:%M", errors="coerce")
    return converted.isna().sum()

print("Missing/Improperly Formatted Departure Times of Day")
departure_tcols = ["Scheduled departure time", "Actual departure time", "Wheels-off time"]
for tcol in departure_tcols:
    print("\t",tcol,":",invalid_times(departures[tcol]))

print("Missing/Improperly Formatted Arrival Times of Day")
arrival_tcols = ["Scheduled Arrival Time", "Actual Arrival Time", "Wheels-on Time"]
for tcol in arrival_tcols:
    print("\t",tcol,":",invalid_times(arrivals[tcol]))

Missing/Improperly Formatted Departure Times of Day
	 Scheduled departure time : 0
	 Actual departure time : 140
	 Wheels-off time : 169
Missing/Improperly Formatted Arrival Times of Day
	 Scheduled Arrival Time : 0
	 Actual Arrival Time : 261
	 Wheels-on Time : 245

In [95]:
# Validate date fields with a similar approach
arrivals_date_col = pd.to_datetime(arrivals["Date (MM/DD/YYYY)"], errors="coerce")
print("Missing Arrivals Dates:",arrivals_date_col.isna().sum())

departures_date_col = pd.to_datetime(departures["Date (MM/DD/YYYY)"], errors="coerce")
print("Missing Departures Dates:",departures_date_col.isna().sum())

Missing Arrivals Dates: 0
Missing Departures Dates: 0

In [113]:
#Validate duration fields are reasonable (between 2 hours early and no more than 24 hours late)
def invalid_duration(col, min_val=-120, max_val=1440):
    mask = col.between(min_val, max_val, inclusive="both")
    return (~mask).sum()

arrivals_duration_cols = ["Scheduled Elapsed Time (Minutes)", 
    "Actual Elapsed Time (Minutes)",
    "Arrival Delay (Minutes)",
    "Taxi-In time (Minutes)",
    "Delay Carrier (Minutes)",
    "Delay Weather (Minutes)",
    "Delay National Aviation System (Minutes)",
    "Delay Security (Minutes)",
    "Delay Late Aircraft Arrival (Minutes)"
    ]

print("="*20,"Arrival Durations Validation","="*20)
for duration_col in arrivals_duration_cols:
    print("Extreme durations in",duration_col,invalid_duration(arrivals[duration_col]))
    
print("="*20,"Departure Durations Validation","="*20)

departures_duration_cols = ["Scheduled elapsed time (Minutes)", 
    "Actual elapsed time (Minutes)",
    "Departure delay (Minutes)",
    "Taxi-Out time (Minutes)",
    "Delay Carrier (Minutes)",
    "Delay Weather (Minutes)",
    "Delay National Aviation System (Minutes)",
    "Delay Security (Minutes)",
    "Delay Late Aircraft Arrival (Minutes)"
    ]
for duration_col in departures_duration_cols:
    print("Extreme durations in",duration_col,invalid_duration(departures[duration_col]))

==================== Arrival Durations Validation ====================
Extreme durations in Scheduled Elapsed Time (Minutes) 0
Extreme durations in Actual Elapsed Time (Minutes) 0
Extreme durations in Arrival Delay (Minutes) 622
Extreme durations in Taxi-In time (Minutes) 0
Extreme durations in Delay Carrier (Minutes) 452
Extreme durations in Delay Weather (Minutes) 9
Extreme durations in Delay National Aviation System (Minutes) 2
Extreme durations in Delay Security (Minutes) 0
Extreme durations in Delay Late Aircraft Arrival (Minutes) 70
==================== Departure Durations Validation ====================
Extreme durations in Scheduled elapsed time (Minutes) 0
Extreme durations in Actual elapsed time (Minutes) 0
Extreme durations in Departure delay (Minutes) 16
Extreme durations in Taxi-Out time (Minutes) 0
Extreme durations in Delay Carrier (Minutes) 1
Extreme durations in Delay Weather (Minutes) 0
Extreme durations in Delay National Aviation System (Minutes) 0
Extreme durations in Delay Security (Minutes) 0
Extreme durations in Delay Late Aircraft Arrival (Minutes) 6

### Duplicate Checks

In [118]:
# Check for duplicates on key columns

key_departure_cols = ["Date (MM/DD/YYYY)","Flight Number","Tail Number","Scheduled departure time"]
dep_duplicate_mask = departures.duplicated(subset=key_departure_cols, keep=False)
print("Potential duplicates in departures:", dep_duplicate_mask.sum())

key_arrival_cols = ["Date (MM/DD/YYYY)","Flight Number","Tail Number","Scheduled Arrival Time"]
arr_duplicate_mask = arrivals.duplicated(subset=key_arrival_cols, keep=False)
print("Potential duplicates in arrivals:", arr_duplicate_mask.sum())

Potential duplicates in departures: 0
Potential duplicates in arrivals: 0

### Outlier Checks

In [125]:
#Check for outliers in float64 columns

def iqr_outliers(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    mask = (series < lower) | (series > upper)
    return mask
    
print("="*20,"Arrivals Outliers","="*20)
arr_float_cols = arrivals.select_dtypes(include="float64").columns
for col in arr_float_cols:
    outliers_mask = iqr_outliers(arrivals[col])
    outliers_pct = outliers_mask.sum() / len(arrivals[col]) * 100
    print("Outliers Percentage in",col,":",round(outliers_pct,2),"%")

print("="*20,"Departures Outliers","="*20)
dep_float_cols = departures.select_dtypes(include="float64").columns
for col in dep_float_cols:
    outliers_mask = iqr_outliers(departures[col])
    outliers_pct = outliers_mask.sum() / len(departures[col]) * 100
    print("Outliers Percentage in",col,":",round(outliers_pct,2),"%")

==================== Arrivals Outliers ====================
Outliers Percentage in Flight Number : 0.0 %
Outliers Percentage in Scheduled Elapsed Time (Minutes) : 1.41 %
Outliers Percentage in Actual Elapsed Time (Minutes) : 4.32 %
Outliers Percentage in Arrival Delay (Minutes) : 9.76 %
Outliers Percentage in Taxi-In time (Minutes) : 3.96 %
Outliers Percentage in Delay Carrier (Minutes) : 9.61 %
Outliers Percentage in Delay Weather (Minutes) : 1.5 %
Outliers Percentage in Delay National Aviation System (Minutes) : 10.01 %
Outliers Percentage in Delay Security (Minutes) : 0.11 %
Outliers Percentage in Delay Late Aircraft Arrival (Minutes) : 10.3 %
==================== Departures Outliers ====================
Outliers Percentage in Flight Number : 0.0 %
Outliers Percentage in Scheduled elapsed time (Minutes) : 1.09 %
Outliers Percentage in Actual elapsed time (Minutes) : 3.78 %
Outliers Percentage in Departure delay (Minutes) : 12.25 %
Outliers Percentage in Taxi-Out time (Minutes) : 7.76 %
Outliers Percentage in Delay Carrier (Minutes) : 16.84 %
Outliers Percentage in Delay Weather (Minutes) : 2.19 %
Outliers Percentage in Delay National Aviation System (Minutes) : 11.46 %
Outliers Percentage in Delay Security (Minutes) : 0.06 %
Outliers Percentage in Delay Late Aircraft Arrival (Minutes) : 13.25 %

### Data Quality Assessment
Based on checks of missing data, duplicate row, reasonableness according to domain expectations, and outlier detections, these datasets can be trusted with no cleaning.

## Phase 3: Cleaning Decisions
Based on the above data quality assessment, we do not have to perform any significant cleaning that will jeopardize the truth.

To make later analyses more efficient, we will concatenate the two datasets, convert time-of-day fields to datetime fields, and drop unneeded columns.

In [133]:
# To merge arrivals and departures, change column names to a common scheme
departures_mod = departures.assign(
    flight_event="Departure", 
    scheduled_time=departures["Scheduled departure time"],
    actual_time=departures["Actual departure time"],
    wheels_time=departures["Wheels-off time"],      
    taxi_time=departures["Taxi-Out time (Minutes)"],
    delay=departures['Departure delay (Minutes)']
)

arrivals_mod = arrivals.assign(
    flight_event="Arrivals", 
    scheduled_time=arrivals["Scheduled Arrival Time"],
    actual_time=arrivals["Actual Arrival Time"],
    wheels_time=arrivals["Wheels-on Time"],      
    taxi_time=arrivals["Taxi-In time (Minutes)"],
    delay=arrivals['Arrival Delay (Minutes)']
)

In [134]:
# Drop the columns that have been renamed
dep_drop_cols = [
    "Scheduled departure time",
    "Actual departure time",
    "Taxi-Out time (Minutes)",
    "Wheels-off time",
    'Departure delay (Minutes)'
]

arr_drop_cols = [
    "Scheduled Arrival Time",
    "Actual Arrival Time",
    "Taxi-In time (Minutes)",
    "Wheels-On time",
    'Arrival Delay (Minutes)'
]

departures_mod = departures_mod.drop(columns=[c for c in dep_drop_cols if c in departures_mod.columns])
arrivals_mod= departures_mod.drop(columns=[c for c in arr_drop_cols if c in departures_mod.columns])

In [136]:
#Concatenate the two data frames
combined = pd.concat([departures_mod, arrivals_mod], ignore_index=True, sort=False)
combined.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),flight_event,scheduled_time,actual_time,wheels_time,taxi_time,delay
0,AA,01/01/2016,5.0,N361AA,HNL,516.0,529.0,121.0,0.0,13.0,0.0,0.0,Departure,12:25,14:26,14:45,19.0,121.0
1,AA,01/01/2016,7.0,N367AA,OGG,509.0,512.0,0.0,0.0,0.0,0.0,0.0,Departure,09:05,09:06,09:29,23.0,1.0
2,AA,01/01/2016,25.0,N3KYAA,PHL,185.0,161.0,0.0,0.0,0.0,0.0,0.0,Departure,12:50,12:43,12:55,12.0,-7.0
3,AA,01/01/2016,37.0,N879AA,SFO,237.0,259.0,19.0,0.0,22.0,0.0,0.0,Departure,18:45,19:04,19:22,18.0,19.0
4,AA,01/01/2016,43.0,N4YEAA,DTW,158.0,157.0,0.0,0.0,0.0,0.0,0.0,Departure,10:45,10:41,11:04,23.0,-4.0

In [137]:
combined.tail()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),flight_event,scheduled_time,actual_time,wheels_time,taxi_time,delay
2764933,AA,12/31/2024,3265.0,N978UY,BDL,194.0,172.0,0.0,0.0,0.0,0.0,0.0,Departure,13:11,13:04,13:13,9.0,-7.0
2764934,AA,12/31/2024,3267.0,N744P,BHM,103.0,92.0,0.0,0.0,0.0,0.0,0.0,Departure,14:55,14:48,15:03,15.0,-7.0
2764935,AA,12/31/2024,3279.0,N711UW,ELP,118.0,105.0,0.0,0.0,0.0,0.0,0.0,Departure,12:26,12:23,12:38,15.0,-3.0
2764936,AA,12/31/2024,3287.0,N994NN,BOS,217.0,207.0,0.0,0.0,0.0,0.0,0.0,Departure,07:05,07:06,07:28,22.0,1.0
2764937,AA,12/31/2024,3295.0,N198UW,LAX,204.0,209.0,0.0,0.0,0.0,0.0,0.0,Departure,13:15,13:16,13:31,15.0,1.0

In [138]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2764938 entries, 0 to 2764937
Data columns (total 18 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   Carrier Code                              object
 1   Date (MM/DD/YYYY)                         object
 2   Flight Number                             float64
 3   Tail Number                               object
 4   Destination Airport                       object
 5   Scheduled elapsed time (Minutes)          float64
 6   Actual elapsed time (Minutes)             float64
 7   Delay Carrier (Minutes)                   float64
 8   Delay Weather (Minutes)                   float64
 9   Delay National Aviation System (Minutes)  float64
 10  Delay Security (Minutes)                  float64
 11  Delay Late Aircraft Arrival (Minutes)     float64
 12  flight_event                              object
 13  scheduled_time                            object
 14  actual_time                               object
 15  wheels_time                               object
 16  taxi_time                                 float64
 17  delay                                     float64
dtypes: float64(10), object(8)
memory usage: 379.7+ MB

In [139]:
#Ensure we only have "AA" as the carrier
print("Arrivals Carrier Codes:",combined["Carrier Code"].value_counts())

Arrivals Carrier Codes: Carrier Code
AA    2764938
Name: count, dtype: int64

In [140]:
#Drop Carrier Code and Tail Number Columns since those are not needed for this analysis
combined.drop(columns=["Carrier Code", "Tail Number"],inplace=True)

In [141]:
#Check for any lingering missing values
combined.isna().sum()

Date (MM/DD/YYYY)                           0
Flight Number                               0
Destination Airport                         0
Scheduled elapsed time (Minutes)            0
Actual elapsed time (Minutes)               0
Delay Carrier (Minutes)                     0
Delay Weather (Minutes)                     0
Delay National Aviation System (Minutes)    0
Delay Security (Minutes)                    0
Delay Late Aircraft Arrival (Minutes)       0
flight_event                                0
scheduled_time                              0
actual_time                                 0
wheels_time                                 0
taxi_time                                   0
delay                                       0
dtype: int64

In [142]:
# Combine the time columns with the date to make valide datetime objects

#Change the Date column to datetime objects
combined["Date (MM/DD/YYYY)"] = pd.to_datetime(combined["Date (MM/DD/YYYY)"])

combined_mod = combined.copy() #Copying to prevent overwriting the original

tcols = ["scheduled_time", "actual_time", "wheels_time"]
for tcol in tcols:
    combined_mod[tcol + "_dt"] = pd.to_datetime(
        combined_mod["Date (MM/DD/YYYY)"].dt.strftime("%Y-%m-%d") + " " + combined_mod[tcol].astype(str),
        format="%Y-%m-%d %H:%M",
        errors="coerce" #Deal with data not in ##:## by replacing with NaN
    )
# Since the above might have resulted in NaNs, drop them again
combined_mod.dropna(inplace=True)

# # Drop the appropriate columns now that they are not needed
combined_mod.drop(columns=tcols, inplace=True)
combined_mod.drop(columns=["Date (MM/DD/YYYY)"], inplace=True)

In [143]:
combined_mod.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2764320 entries, 0 to 2764937
Data columns (total 15 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   Flight Number                             float64
 1   Destination Airport                       object
 2   Scheduled elapsed time (Minutes)          float64
 3   Actual elapsed time (Minutes)             float64
 4   Delay Carrier (Minutes)                   float64
 5   Delay Weather (Minutes)                   float64
 6   Delay National Aviation System (Minutes)  float64
 7   Delay Security (Minutes)                  float64
 8   Delay Late Aircraft Arrival (Minutes)     float64
 9   flight_event                              object
 10  taxi_time                                 float64
 11  delay                                     float64
 12  scheduled_time_dt                         datetime64[ns]
 13  actual_time_dt                            datetime64[ns]
 14  wheels_time_dt                            datetime64[ns]
dtypes: datetime64[ns](3), float64(10), object(2)
memory usage: 337.4+ MB