# Introduction
### Source Data
* **United States Department of Transportation - U.S. Buerau of Transportation Statistics (Airlines, Airport, and Aviation)**
    
    URL: https://transtats.bts.gov/Fields.asp?gnoyr_VQ=FGJ

* **Federal Aviation Administration Aircraft Registration Database**
    
    URL: https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download

# Initial Questions
1. What do we want to know about airline on-time performance?
2. How will the answer be useful in decision making?

# Data Specific Questions
**1. How does on-time performance vary across carrier, airports, time, day, maybe aircraft?**
   
    -  What's the overall distribution of any flight delays? 
    -  What airline has the best and worst on-time performance? 
    -  How do routes (short/long) correlate with performance? 
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    

**2. What delay propagation patterns can we draw?**

    - Is there recovery or do they compound / propagate? 
            - Are some airlines better at recovering than others? 
        - What information can we draw from taxi times? Thinking about traffic jams at the runways due to built up delays
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What is the average total time per day in delays a carrier has? 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 

**3. What factors have the greatest effect on on-time performance**
   
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delau
        - What is the total number 

4. What is the overall cost of delays?
    -Fuel, labor, etc. 

6. What is the impact to customers?
    - Which airports should customers expect delays
    - What percent of flights are delayed 15, 30, 60+ minutes?


## Brandon Analysis Questions
    -  How do routes correlate with performance? 
    - What are the max, min, and average flight times? Is there a relationships to flight length and delays
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    - How resilient is each carrier to delay shocks?
        - What % of flights recover to on-time after a delay?
    - What is the % chance that a late arrival will cause the next flight to also be late T
    - What is the average total time per day in delays a carrier has? 
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Are taxi times leading indicators of airport congestion?
        - What is the relationship between taxi out times and departure delays (Wheels off)
    
## Trace Analysis Questions
    -  What's the overall distribution of any flight delays? 
    - What airports have the highest delays?
    -  What airline has the best and worst on-time performance? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delay?
    - What is the likelyhood of a delay based on airline, airport, and time of day?
    - What aircraft have the highest carrier delays?
    - What day of the week has the highest delays?

## Amibtion
- What is the cost to airlines due to delays? Per day? Per Year?
- 

# Key Features Needed
### 1. Date

### 2. Time of Day

### 3. Carrier
- American
- United
- Delta
- Southwest
- Alaska
- JetBlue
- Spirit
- Frontier

### 5. Airport (Departure)
- Dallas Fort-Worth (DFW) **1**
- Atlanta (ATL)           **2**
- Los Angeles (LAX)       **3**
- New York                **6**
  - JFK
- Miami (MIA)             **8**
- Chicago O'Hare (OHD)    **4**
- Phoenix (PHX)           **7**
- Denver (DEN)            **5**
- San Franscisco (SFO)
- Washington D.C.
  - Dulles (IAD)

**I was thinking we could just narrow it down to 5-10 airports but since we have the airport IDs in the data, I don't entirely see the benefit of just picking 10 other than maybe lessening the complexity or size of the data. Maybe we could just do some groupings by U.S. region? Open to suggestions**


### 7. Airport (Arrival) / Destination

### 8. Reason For Delay
- Weather
- Carrier
- Security
- Late Aircraft
- National Aviation System (NAS)

**we can leave these split up into their own feature**

### 9. Tail Number

### 10. Elapsed Time

### 11. State

### 12. Wheels Up

### 13. Wheel Down

### 14. Taxi Time (We could create a column that sums up taxi out and taxi in. However, taxi out could be an important variable for assessing NAS delays)

# 1. Initial Load & Reconniassance 
## Questions to Answer
1. Tidy or not?
2. Entities, Attributes, Observations?
3. Variable Types?
4. Shape & scale?
5. Any obvious problems?

**I will add a table of feature names and a brief description for each so it's easy to follow the table**

### Hypothessis
- Relationships worth exploring
    - Numeric
    - Categorical
    - Numeric vs Categorical
    - Numeric vs Numeric 
    -  on-time performance vs. time of day
    -  on-time performance vs carrier
    -  on-time performance vs airport
    -  Carrier vs % of flights delayed
    -  Carrier vs departure / arrival delays

-

# Importing All Necessary Packages

In [21]:
import pandas as pd
import numpy as np
from pathlib import Path
import zipfile
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Reading In All The Source Data

In [22]:
df = pd.read_parquet("../data/bts_all.parquet")
df_aircraft = pd.read_csv("../data/Aircraft.csv")
df_airports = pd.read_csv("../data/Airports.csv")
df_airline = pd.read_csv("../data/Airline.csv")
df.head()

,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,...,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest
0,2022-11-23,OH,N513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,51.0,313.0,28.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN
1,2022-11-27,OH,N538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,51.0,313.0,2.0,0.0,13.0,0.0,50.0,NaN,0.0,NaN
2,2022-11-28,OH,N522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,56.0,313.0,0.0,0.0,8.0,0.0,55.0,NaN,0.0,NaN
3,2022-11-29,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,50.0,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,2022-11-30,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1819,...,NaN,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

# Initial Reconnaissance

In [23]:
df.info()
#df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 31 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          object
 1   Reporting_Airline   object
 2   Tail_Number         object
 3   Origin              object
 4   OriginCityName      object
 5   OriginStateName     object
 6   Dest                object
 7   DestCityName        object
 8   DestStateName       object
 9   CRSDepTime          int64
 10  DepDelay            float64
 11  TaxiOut             float64
 12  WheelsOff           float64
 13  WheelsOn            float64
 14  TaxiIn              float64
 15  CRSArrTime          int64
 16  ArrDelay            float64
 17  Cancelled           float64
 18  CancellationCode    object
 19  Diverted            float64
 20  ActualElapsedTime   float64
 21  AirTime             float64
 22  Distance            float64
 23  CarrierDelay        float64
 24  WeatherDelay        float64
 25  NASDelay            float64
 26  SecurityDelay       float64
 27  LateAircraftDelay   float64
 28  TotalAddGTime       float64
 29  DivAirportLandings  float64
 30  DivReachedDest      float64
dtypes: float64(19), int64(2), object(10)
memory usage: 8.2+ GB

# Updating Dtypes

In [24]:
df['FlightDate'] = pd.to_datetime(df['FlightDate'], errors="coerce") #Displaying only date for Flight Date
#df['FlightDate'] = df['FlightDate'].dt.strftime("%d/%m/%Y") #Formatting date to be in dd/mm/yyyy format

df['CRSDepTime'] = df['CRSDepTime'].astype(str).str.zfill(4) #Converting int64 to 4 digit string
df['CRSArrTime'] = df['CRSArrTime'].astype(str).str.zfill(4) #Converting int64 to 4 digit string
df['CRSDepTime'] = pd.to_datetime(df['CRSDepTime'], format="%H%M", errors='coerce') #Converting string to datetime with format proper hours and minutes format. Any invalid values will become NaT
df['CRSArrTime'] = pd.to_datetime(df['CRSArrTime'], format="%H%M", errors='coerce') #Converting string to datetime with format proper hours and minutes format. Any invalid values will become NaT
df.info()
#df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 31 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          datetime64[ns]
 1   Reporting_Airline   object
 2   Tail_Number         object
 3   Origin              object
 4   OriginCityName      object
 5   OriginStateName     object
 6   Dest                object
 7   DestCityName        object
 8   DestStateName       object
 9   CRSDepTime          datetime64[ns]
 10  DepDelay            float64
 11  TaxiOut             float64
 12  WheelsOff           float64
 13  WheelsOn            float64
 14  TaxiIn              float64
 15  CRSArrTime          datetime64[ns]
 16  ArrDelay            float64
 17  Cancelled           float64
 18  CancellationCode    object
 19  Diverted            float64
 20  ActualElapsedTime   float64
 21  AirTime             float64
 22  Distance            float64
 23  CarrierDelay        float64
 24  WeatherDelay        float64
 25  NASDelay            float64
 26  SecurityDelay       float64
 27  LateAircraftDelay   float64
 28  TotalAddGTime       float64
 29  DivAirportLandings  float64
 30  DivReachedDest      float64
dtypes: datetime64[ns](3), float64(19), object(9)
memory usage: 8.2+ GB

In [5]:
#Aircraft.csv
df['Tail_Number'] = df['Tail_Number'].str.lstrip('N') #Removing leading "N" from Tail Number (this is to be able to properly match the tail number with the correct make and model aircraft from the Aircraft.csv

df_aircraft = df_aircraft.drop(columns='MFR MDL CODE') #Dropping column, 'MFR MDL CODE' in aircraft DF

df_aircraft = df_aircraft.rename(columns= { #Changing feature names for Aircraft.csv
    'N-NUMBER': 'Tail_Number',
    'MFR': 'Manufacturer',
    'NO-SEATS': 'Number_of_Seats'
})
df = df.merge(df_aircraft, on='Tail_Number', how='left') #Merging Aircraft DF

#Airport.csv
dep_airports = df_airports.copy()
dep_airports = dep_airports.rename(columns={'lid': 'DepAirport_code',
                                          'country': 'dep_country'})
df = df.merge(dep_airports[['DepAirport_code', 'dep_country']], left_on='Origin', right_on='DepAirport_code', how='left')

dest_airports = df_airports.copy()
dest_airports = dest_airports.rename(columns={'lid': 'DestAirport_code',
                                          'country': 'dest_country'})
df = df.merge(dest_airports[['DestAirport_code', 'dest_country']], left_on='Dest', right_on='DestAirport_code', how='left')

mask = (df['dep_country'] != 'US') | (df['dest_country'] != 'US')
df.loc[mask, 'international'] = 'International'
df.loc[~mask, 'international'] = 'Domestic'
df = df.drop(columns=['DepAirport_code', 'dep_country', 'DestAirport_code', 'dest_country'])

#Airline.csv
df_airline = df_airline.rename(columns= {'OP_UNIQUE_CARRIER': 'Reporting_Airline'})
df = df.merge(df_airline, on='Reporting_Airline', how='left')
df = df.rename(columns= { 'international': 'flight_type',
                          'Description': 'Airline'})
df['Airline'] = df['Airline'].replace({
    'American Airlines Inc.': 'American Airlines',
    'Alaska Airlines Inc.': 'Alaska Airlines',
    'Delta Air Lines Inc.': 'Delta Airlines',
    'Frontier Airlines Inc.': 'Frontier Airlines',
    'Hawaiian Airlines Inc.': 'Hawaiian Airlines',
    'PSA Airlines Inc.': 'PSA Airlines',
    'Skywest Airlines Inc.': 'Skywest Airlines',
    'United Air Lines Inc.': 'United Airlines',
    'Southwest Airlines Co.': 'Southwest Airlines',
})        
df = df.drop(columns=['Reporting_Airline'])
df

,FlightDate,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,DepDelay,...,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest,Manufacturer,MODEL,Number_of_Seats,flight_type,Airline
0,2022-11-23,513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,29.0,...,0.0,0.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
1,2022-11-27,538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,52.0,...,0.0,50.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
2,2022-11-28,522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,55.0,...,0.0,55.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
3,2022-11-29,526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,-11.0,...,NaN,NaN,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
4,2022-11-30,526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:19:00,NaN,...,NaN,NaN,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35417935,2022-06-21,345DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,0.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417936,2022-06-21,345DN,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,1900-01-01 11:07:00,18.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417937,2022-06-22,117DX,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,4.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417938,2022-06-22,117DX,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,1900-01-01 11:07:00,15.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417939,2022-06-23,396DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,-2.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines

In [25]:
#Checking that earliest date of dataset to be January 1, 2020
earliest_flight = df['FlightDate'].min()
latest_flight = df['FlightDate'].max()
print("Earliest Flight Date:", earliest_flight.date())
print("Latest Flight Date:", latest_flight.date())

Earliest Flight Date: 2020-01-01
Latest Flight Date: 2025-07-31

In [26]:
df.columns.tolist()

['FlightDate',
 'Reporting_Airline',
 'Tail_Number',
 'Origin',
 'OriginCityName',
 'OriginStateName',
 'Dest',
 'DestCityName',
 'DestStateName',
 'CRSDepTime',
 'DepDelay',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrDelay',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'ActualElapsedTime',
 'AirTime',
 'Distance',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'TotalAddGTime',
 'DivAirportLandings',
 'DivReachedDest']

In [28]:
#df.info()

In [27]:
#df.describe

In [28]:
df.shape

(35417940, 35)

In [20]:
air_unique = df['Airline'].unique().tolist() #Show number of unique airlines in the main DF
air_counts = df['Airline'].value_counts(dropna=False) #Count # of occurrences for each unique airline, including rows with NaN values. We will drop rows with NaN later
air_show = df[df['Airline'].isna()].head(5) #Show first 5 rows of observations with NaN for airline
df = df.dropna(subset=['Airline']) #Drop rows with now company airline. These are likely private carriers we want to exclude. Only looking to capture major airlines

,FlightDate,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,DepDelay,...,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest,Manufacturer,MODEL,Number_of_Seats,flight_type,Airline
0,2022-11-23,513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,29.0,...,0.0,0.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
1,2022-11-27,538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,52.0,...,0.0,50.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
2,2022-11-28,522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,55.0,...,0.0,55.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
3,2022-11-29,526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,-11.0,...,NaN,NaN,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
4,2022-11-30,526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:19:00,NaN,...,NaN,NaN,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35417935,2022-06-21,345DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,0.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417936,2022-06-21,345DN,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,1900-01-01 11:07:00,18.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417937,2022-06-22,117DX,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,4.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417938,2022-06-22,117DX,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,1900-01-01 11:07:00,15.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines
35417939,2022-06-23,396DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,-2.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Airlines

# What airports have the highest/worst delays?

In [ ]:
airports_lst = df['airports']

# 2. Data Quality
- What is broken, missing, or suspicious?
- Are the dtypes correct for each variable?
- Do the values make sense?
- Where is data missing and how much?
- Are there duplicates or outliers?
- Is the data trustworthy as is?

# 3. Cleaning Decisions
- Motivation
    - How do I fix problems without corrupting the truth?
- Questions
    - Drop or fix? What's the impact on the analysis?
    - What the missingness mechanism (MCAR / MAR / MNAR)
    - Are outliers legit or are they errors?
    - What assumptions am I making?
- Hypothesis & Iteration
    - What biases might my cleaning decisions introduce
    - What sensitivity analyses should I run?
- Iteration Signals
    - Cleaning reveals new issues --> back to phase 2
    - Decisions feel arbitrary --> need domain expertise

# 4. Statistical EDA
### Content From Lecture 13a 
-Motivation

    - What patterns, relationships stories exist in the data?
-Driving Questions

    - What's "typical" for each variable?
    - How do variables relate to each other?
    - Do patterns hold across subgroups?
    What surprises emerge?

### Project

- Motivation
    -fdfsf

- Driving Questions

# 5. Transformation

# 6. Save & Document

# Brandon Inputs

In [ ]:
df.tail()

In [ ]:
df_aircraft = pd.read_csv("../data/Raw/Aircraft.csv")
df_aircraft

In [ ]:
#Changing feature names for aircraft DF
mod_aircraft = df_aircraft.rename(columns= {
    'N-NUMBER': 'Tail_Number',
    'MFR': 'Manufacturer',
    'NO-SEATS': 'Number_of_Seats'
})
mod_aircraft

df_merged = df.merge(mod_aircraft, on='Tail_Number', how='left')
df_merged

### How do routes correlate with delays?
We're looking to assess how delays vary by route. In this context, we'll define a route as a departure/arrival airport pair.  We are interested in identifying the routes with the highest average delay per flight.

In [ ]:
#create a route column from origin and destination columns
df["route"] = df["Origin"] + "_" + df["Dest"]

#build a dataframe of flight delay information for each route
route_delay = (
    df.groupby("route")
      .agg(total_arr_delay=("ArrDelay", "sum"),
           n_flights=("ArrDelay", "count"))
      .sort_values("n_flights", ascending=False)
)

In [ ]:
route_delay['avg_delay_per_flight'] = route_delay['total_arr_delay'] / route_delay['n_flights']
route_delay.head()

#### Establish a minimum number of flights
To avoid the results being skewed by routes with very few flights, we'll establish a minimum threshold of number of flights in order for a route to be considered in the analysis. To do this, we'll start with a cutoff that includes 80% of all flights and adjust as necessary.

In [ ]:
# Compute the cumulative percentage of total flights as routes are sorted by descending flight count
route_delay["cumulative_share"] = route_delay["n_flights"].cumsum() / route_delay["n_flights"].sum()
route_delay

In [ ]:
#Establish 80% cutoff mark
cutoff_row = route_delay[route_delay["cumulative_share"] >= 0.80].iloc[0]
cutoff_value = cutoff_row["n_flights"]
cutoff_value

In [ ]:
plt.figure(figsize=(14,6))
sns.barplot(
    data=route_delay.sort_values("n_flights", ascending=False),
    x=route_delay.sort_values("n_flights", ascending=False).index,
    y="n_flights",
    color="steelblue"
)
plt.title("Number of Flights per Route (Sorted)")
plt.xlabel("Route (sorted by flight volume)")
plt.ylabel("Number of Flights")
plt.xticks([], [])   #hide x-axis labels
plt.show()

In [ ]:
sns.histplot(route_delay["n_flights"], bins=100)
plt.title("Distribution of Route Flight Counts")
plt.xlabel("Number of Flights")
plt.ylabel("Number of Routes")
plt.show()

Given the above histogram and bar char, there is a long tail of lower-volume routes that might be of interest.  Let's up the threshold to 95% of flights.

In [ ]:
#Establish 95% cutoff mark
cutoff_row = route_delay[route_delay["cumulative_share"] >= 0.95].iloc[0]
cutoff_value = cutoff_row["n_flights"]
cutoff_value

A minimum threshold of 1623 flights for a route covers 95% of all flights. Now, we'll find the average delay time per flight for all routes with 1623 flights or more.

In [ ]:
min_flights = 1623


filtered_routes = route_delay[route_delay["n_flights"] >= min_flights]

# Sort by highest avg delay per flight
filtered_routes = filtered_routes.sort_values(
    "avg_delay_per_flight",
    ascending=False
)
filtered_routes.drop(columns=["cumulative_share"], inplace=True) # cumulative share doesn't make sense in this context

In [ ]:
worst_routes = filtered_routes.head()
worst_routes

In [ ]:
best_routes = filtered_routes.tail()
best_routes

Based on this analysis, there is no standout commonality among the best and worst routes for delays or early arrivals.  Let's explore volume per day at the airports in the top 5 and bottom 5 in the delay data to see if there is a signal there.

In [ ]:
top_worst_airports = ["BDL", "SJU", "DCA", "ASE", "DFW", "MDT", "EYW", "PHL"]
top_best_airports  = ["BTM", "SLC", "KOA", "OAK", "RHI", "MSP", "TYS", "DTW", "LIH", "DEN"]

airport_daily_volume = (
    df.melt(
        id_vars=["FlightDate"],
        value_vars=["Origin", "Dest"],
        var_name="type",
        value_name="airport"
    )
    .groupby(["airport", "FlightDate"])
    .size()
    .reset_index(name="flights_per_day")
)

In [ ]:
# Average volume / day at the airports in the worst routes
worst_filtered = (
    airport_daily_volume[airport_daily_volume["airport"].isin(top_worst_airports)]
)
worst_filtered_avg = worst_filtered.groupby("airport")["flights_per_day"].mean()

In [ ]:
# Average volume / day at the airports in the best routes
best_filtered = (
    airport_daily_volume[airport_daily_volume["airport"].isin(top_best_airports)]
)
best_filtered_avg = best_filtered.groupby("airport")["flights_per_day"].mean()

In [ ]:
def create_route_volume_df(route_df,filtered_avg):
    """
    Given a dataframe of routes and a series of averages,
    create a dataframe of routes with volume totals and differences
    """
    rows = []
    for route in route_df.index:
        origin,dest = route.split("_")
        volume_diff = filtered_avg[origin] - filtered_avg[dest]
        total_volume = filtered_avg[origin] + filtered_avg[dest]
        rows.append({
            "route": route,
            "origin": origin,
            "dest": dest,
            "volume_diff": volume_diff,
            "total_volume": total_volume
        })
    
    return pd.DataFrame(rows).set_index("route")

In [ ]:
best_route_volumes_df = create_route_volume_df(best_routes,best_filtered_avg)
best_route_volumes_df

In [ ]:
worst_route_volumes_df = create_route_volume_df(worst_routes,worst_filtered_avg)
worst_route_volumes_df

In [ ]:
#Best vs Worst Average Total Volumes
print("Best Route Total Volume:",best_route_volumes_df['total_volume'].mean())
print("Worst Route Total Volume:",worst_route_volumes_df['total_volume'].mean())

In [ ]:
#Best vs Worst Average Volume Difference
print("Best Route Volume Diff:",best_route_volumes_df['volume_diff'].mean())
print("Worst Route Volume Diff:",worst_route_volumes_df['volume_diff'].mean())

There is signal in both the difference and totals in volumes between an origin and destination for more exploration. Next, we'll do a regression of these two variables on the entire set.

In [ ]:
avg_daily_volume = airport_daily_volume.groupby("airport")["flights_per_day"].mean()
route_volume_df = create_route_volume_df(route_delay,avg_daily_volume)

In [ ]:
merged_route_volumes = route_volume_df.merge(route_delay,on="route")

In [ ]:
merged_route_volumes = merged_route_volumes[merged_route_volumes["n_flights"] >= min_flights]
merged_route_volumes.head()

In [ ]:
#Single Variate Regression for volume difference
X = merged_route_volumes[["volume_diff"]] #predictor
y = merged_route_volumes["avg_delay_per_flight"] #predictand

X = sm.add_constant(X) #Intercept

# Fit model
model = sm.OLS(y, X).fit()

print(model.summary())

In [ ]:
#Plot Avg Delay per FLight vs Volume Difference

x = merged_route_volumes["volume_diff"]
y = merged_route_volumes["avg_delay_per_flight"]

# Fit linear trend
m, b = np.polyfit(x, y, 1)

plt.figure(figsize=(8,5))
plt.scatter(x, y, alpha=0.4, label="Data")
plt.plot(x, m*x + b, color="red", label="Trend Line")

plt.xlabel("Volume Difference (Origin - Destination)")
plt.ylabel("Average Delay per Flight (min)")
plt.title("Avg Delay per Flight vs Volume Difference")
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
#Single Variate Regression for total volume
X = merged_route_volumes[["total_volume"]] #predictor
y = merged_route_volumes["avg_delay_per_flight"] #predictand

X = sm.add_constant(X) #Intercept

# Fit model
model = sm.OLS(y, X).fit()

print(model.summary())

In [ ]:
#Plot Avg Delay per FLight vs Total Volume

x = merged_route_volumes["total_volume"]
y = merged_route_volumes["avg_delay_per_flight"]

# Fit linear trend
m, b = np.polyfit(x, y, 1)

plt.figure(figsize=(8,5))
plt.scatter(x, y, alpha=0.4, label="Data")
plt.plot(x, m*x + b, color="red", label="Trend Line")

plt.xlabel("Total Volume (Origin + Destination)")
plt.ylabel("Average Delay per Flight (min)")
plt.title("Avg Delay per Flight vs Total Volume")
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
The total volume of both origin and destination is slightly better predictor of average delay (1.8% contribution to variance based on R-squared) than the volume difference (~0.3% contribution) but both are tiny.  Next, we'll explore the relationship between flight distance and average delay.

In [ ]:
# Initial Histogram of distances
plt.figure(figsize=(10,4))
sns.histplot(df["Distance"], bins=50)
plt.title("Distribution of Flight Distance")
plt.xlabel("Distance (miles)")
plt.show()

In [ ]:
#Random sampling of flight distances vs delays
plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df.sample(50000, random_state=42),  
    x="Distance",
    y="ArrDelay",
    alpha=0.25
)
plt.title("Flight Distance vs Arrival Delay")
plt.xlabel("Distance (miles)")
plt.ylabel("Arrival Delay (min)")
plt.grid(True)
plt.show()

In [ ]:
corr = df["Distance"].corr(df["ArrDelay"])
corr

Correlation (R-squared) is near 0.  As expected, there is almost no relationship between flight delay and length, at least as a predictor.

In [ ]:
dep = df.copy()

# Convert the FlightDate columnn to datetime
dep["FlightDate"] = pd.to_datetime(dep["FlightDate"], errors="coerce")
dep

In [ ]:
# Turn departure time into a datetime object for better analysis
# This require combining the time information with flight date

# Prep a series of strings to comibe with flight dates
crs_str = (
    dep["CRSDepTime"]
    .astype(str)
    .str.zfill(4)     # "0730", "1745"
)

# Combine FL_DATE + hh:mm into a true datetime
dep["CRSDepDateTime"] = pd.to_datetime(
    dep["FlightDate"].dt.strftime("%Y-%m-%d") + " " +
    crs_str.str.slice(0, 2) + ":" + crs_str.str.slice(2, 4),
    format="%Y-%m-%d %H:%M",
    errors="coerce"
)

# Drop any rows where we still failed to build a datetime
dep = dep[dep["CRSDepDateTime"].notna()].copy()

In [ ]:
#Check to see how many rows we lost in the operation
rows_lost = len(df.index) - len(dep.index)
rows_lost

We'll first examine the hours of day with the highest and lowest average delay to check for a signal worth exploring.

In [ ]:
#  Create Hourly Delay Stats

dep["dep_hour"] = dep["CRSDepDateTime"].dt.hour  # 0–23

hourly_dep_delay = (
    dep.groupby("dep_hour")["DepDelay"]
      .agg(
          n_flights="size",
          avg_dep_delay="mean",
          median_dep_delay="median",
          pct_delayed_15=lambda s: (s >= 15).mean(),
          pct_on_time_or_early=lambda s: (s <= 0).mean()
      )
      .reset_index()
      .sort_values("dep_hour")
)

hourly_dep_delay

In [ ]:
# Hours with the lowest average departure delay
least_delay_hours = (
    hourly_dep_delay
    .sort_values("avg_dep_delay")
    .head(5)
)

# Hours with the highest average departure delay
most_delay_hours = (
    hourly_dep_delay
    .sort_values("avg_dep_delay", ascending=False)
    .head(5)
)

print("Departure hours with lowest average delay:")
display(least_delay_hours)

print("Departure hours with hgihest average delay:")
display(most_delay_hours)

In [ ]:
bins = [0, 6, 10, 14, 18, 22, 24]
labels = [
    "Late Night (00–05)",
    "Morning (06–09)",
    "Late Morning (10–13)",
    "Afternoon (14–17)",
    "Evening (18–21)",
    "Late Evening (22–23)",
]

dep["dep_hour"] = dep["CRSDepDateTime"].dt.hour
dep["dep_window"] = pd.cut(dep["dep_hour"], bins=bins, labels=labels, right=False)

window_delay = (
    dep.groupby("dep_window")["DepDelay"]
      .agg(
          n_flights="size",
          avg_dep_delay="mean",
          median_dep_delay="median",
          pct_delayed_15=lambda s: (s >= 15).mean(),
          pct_on_time_or_early=lambda s: (s <= 0).mean()
      )
      .sort_values("avg_dep_delay")
)

window_delay

In [ ]:
plt.figure(figsize=(10, 5))
sns.barplot(
    data=window_delay,
    x="dep_window",
    y="avg_dep_delay"
)
plt.xticks(rotation=30, ha="right")
plt.xlabel("Departure Time Window")
plt.ylabel("Average Departure Delay (minutes)")
plt.title("Average Departure Delay by Departure Time Window")
plt.tight_layout()
plt.show()

#### Conclusion
It's clear that morning flights (6 to 9am) are the best in terms of delays, while afternoon flights are more delay prone.

### Weather Effects on Delays
We'll examine how weather causes delays.  We'll start the exploration with exploring the distribution of delay times throughout the year as well as geographically.

In [ ]:
dep["month"] = dep["FlightDate"].dt.month_name()
dep["month_num"] = dep["FlightDate"].dt.month 

monthly_delay_stats = (
    dep.groupby(["month_num", "month"])["ArrDelay"]
      .agg(
          n_flights="size",
          mean_delay="mean",
          median_delay="median",
          p90_delay=lambda s: s.quantile(0.90),
          total_delay="sum"
      )
      .sort_index()   
)

monthly_delay_stats

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(
    data=monthly_delay_stats.reset_index(),
    x="month",
    y="mean_delay",
    order=monthly_delay_stats.reset_index()["month"]
)
plt.xticks(rotation=45)
plt.ylabel("Average Total Delay (mins)")
plt.title("Average Departures Delay per Flight by Month")
plt.tight_layout()
plt.show()

In [ ]:
#Plotting Flights per month to control for effect of volume on delays
flights_per_month = (
    dep.groupby(["month_num", "month"])
      .size()
      .reset_index(name="n_flights")
      .sort_values("month_num")
)

flights_per_month

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(
    data=flights_per_month,
    x="month",
    y="n_flights",
    order=flights_per_month["month"]
)

plt.xticks(rotation=45)
plt.xlabel("Month")
plt.ylabel("Number of Flights")
plt.title("Total Number of Flights per Month")
plt.tight_layout()
plt.show()

The relatively uniform distribution of flights tells us we can neglect volume as a factor in monthly delays.  This aligns to our earlier finding that total volume and volume difference contribute very little to delays.

In [ ]:
#For averaging purposes, count the number of years each month appears in the record
month_year_count_dict = (
    dep.groupby(dep["FlightDate"].dt.month_name())["FlightDate"]
      .apply(lambda s: s.dt.year.nunique())
      .to_dict()
)
month_year_count_df = (
    pd.DataFrame.from_dict(month_year_count, orient="index", columns=["month_count"])
)
month_year_count_df

In [ ]:
wx_delay_totals_by_month = dep.groupby("month")["WeatherDelay"].sum()
monthly_avg_wx_delay = wx_delay_totals_by_month / month_year_count_df["month_count"]
monthly_avg_wx_delay
monthly_avg_wx_delay_df = monthly_avg_wx_delay.reset_index()
monthly_avg_wx_delay_df.columns = ["month", "avg_minutes"]

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(
    data=monthly_avg_wx_delay_df,
    x="month",
    y="avg_minutes",
    order=wx_by_month["month"]
)

plt.xticks(rotation=45)
plt.xlabel("Month")
plt.ylabel("Average Weather Delay (minutes)")
plt.title("Average Weather Delay Minutes per Month")
plt.tight_layout()
plt.show()

It's apparent the average weather delay per month follows a similar pattern to avereage dealy per flight per month.  Now, we'll examine the percentage of flights with any delay that also had a weather delay on a monthly basis.

In [ ]:
#Create a binary column that indicates whether a delay of any type occurred.
#Logic is if either arrival or departure delay is positive, set to 1, otherwise 0
dep["AnyDelay"] = ((dep["DepDelay"] > 0) | (dep["ArrDelay"] > 0)).astype(int)
dep["AnyDelay"]

In [ ]:
monthly_weather_pct = (
    dep.groupby(["month_num", "month"])
      .apply(lambda g: (
          ((g["AnyDelay"] == 1) & (g["WeatherDelay"] > 0)).sum() /
          (g["AnyDelay"] == 1).sum()
      ))
      .reset_index(name="pct_anydelay_with_weather")
      .sort_values("month_num")
)

monthly_weather_pct["pct_anydelay_with_weather"] *= 100
monthly_weather_pct

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(
    data=monthly_weather_pct,
    x="month",
    y="pct_anydelay_with_weather",
    order=monthly_weather_pct["month"]
)

plt.xticks(rotation=45)
plt.ylabel("% of Delayed Flights with Weather Delay")
plt.title("Share of Delayed Flights Attributable to Weather (Monthly)")
plt.tight_layout()
plt.show()

It's clear the weather shares a similar pattern to the overall delays by month, but the low percentages indicate weather isn't generally a major contributor to overall delays. To get a sense of where weather is most likely to be an issue, let's examine the weather delays at the top 100 airports by volume.

In [ ]:
#Create a dataframe of airports with total volume
airport_volume = (
    df.melt(
        id_vars=["FlightDate"],
        value_vars=["Origin", "Dest"],
        var_name="role",
        value_name="airport"
    )
    .groupby("airport")
    .size()
    .reset_index(name="flight_volume")
)
airport_volume

In [ ]:
top100_airports = (
    airport_volume
    .sort_values("flight_volume", ascending=False)
    .head(100)["airport"]
    .tolist()
)

In [ ]:
df["WeatherDelay"] = df["WeatherDelay"].fillna(0)

airport_weather = (
    df.melt(
        id_vars=["WeatherDelay"],
        value_vars=["Origin", "Dest"],
        var_name="role",
        value_name="airport"
    )
    .query("airport in @top100_airports")   # keep only top 100
    .groupby("airport")["WeatherDelay"]
    .sum()
    .reset_index(name="total_weather_delay")
    .sort_values("total_weather_delay", ascending=False)
)

In [ ]:
#Normalize by volume


top100_volume = airport_volume[airport_volume["airport"].isin(top100_airports)]

airport_weather_rate = (
    airport_weather
    .merge(top100_volume, on="airport", how="left")
)

#minnutes per flight
airport_weather_rate["minutes_per_flight"] = (
    airport_weather_rate["total_weather_delay"] /
    airport_weather_rate["flight_volume"]
)

#sort to improve the plot
airport_weather_rate = airport_weather_rate.sort_values(
    "minutes_per_flight",
    ascending=False
)

In [ ]:
plt.figure(figsize=(14,12))

sns.barplot(
    data=airport_weather_rate,
    y="airport",
    x="minutes_per_flight",
    palette="magma"
)

plt.title("Weather Delay Minutes per Flight for Top 100 Airports")
plt.xlabel("Weather Delay Minutes per Flight")
plt.ylabel("Airport")
plt.tight_layout()
plt.show()

In [ ]:
airport_weather_rate.head()

Note the 3 of the top 5 airports for weather delay rate are small regional airports with high volumes.  This indicates that the smaller airports are less equipped to deal with weather impacts and slightly more prone to weather delays.

#### Weather Delay Conclusions
Based on our analysis, it appears weather delays are overall a minor contributor to the probability of flight delay. There are seasonal variations, but, generally, making flight decisions based on weather factors is not advised, especially if flying through major hubs.