# Introduction
### Source Data
* **United States Department of Transportation - U.S. Buerau of Transportation Statistics (Airlines, Airport, and Aviation)**
    
    URL: https://transtats.bts.gov/Fields.asp?gnoyr_VQ=FGJ

* **Federal Aviation Administration Aircraft Registration Database**
    
    URL: https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download

# Initial Questions
1. What do we want to know about airline on-time performance?
2. How will the answer be useful in decision making?

# Data Specific Questions
**1. How does on-time performance vary across carrier, airports, time, day, maybe aircraft?**
   
    -  What's the overall distribution of any flight delays? 
    -  What airline has the best and worst on-time performance? 
    -  How do routes (short/long) correlate with performance? 
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    

**2. What delay propagation patterns can we draw?**

    - Is there recovery or do they compound / propagate? 
            - Are some airlines better at recovering than others? 
        - What information can we draw from taxi times? Thinking about traffic jams at the runways due to built up delays
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What is the average total time per day in delays a carrier has? 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 

**3. What factors have the greatest effect on on-time performance**
   
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delau
        - What is the total number 

4. What is the overall cost of delays?
    -Fuel, labor, etc. 

6. What is the impact to customers?
    - Which airports should customers expect delays
    - What percent of flights are delayed 15, 30, 60+ minutes?


## Brandon Analysis Questions
    -  How do routes correlate with performance? 
    - What are the max, min, and average flight times? Is there a relationships to flight length and delays
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    - How resilient is each carrier to delay shocks?
        - What % of flights recover to on-time after a delay?
    - What is the % chance that a late arrival will cause the next flight to also be late T
    - What is the average total time per day in delays a carrier has? 
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Are taxi times leading indicators of airport congestion?
        - What is the relationship between taxi out times and departure delays (Wheels off)
    
## Trace Analysis Questions
    -  What's the overall distribution of any flight delays? 
    - What airports have the highest delays?
    -  What airline has the best and worst on-time performance? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delay?
    - What is the likelyhood of a delay based on airline, airport, and time of day?
    - What aircraft have the highest carrier delays?
    - What day of the week has the highest delays?

## Amibtion
- What is the cost to airlines due to delays? Per day? Per Year?
- 

# Key Features Needed
### 1. Date

### 2. Time of Day

### 3. Carrier
- American
- United
- Delta
- Southwest
- Alaska
- JetBlue
- Spirit
- Frontier

### 5. Airport (Departure)
- Dallas Fort-Worth (DFW) **1**
- Atlanta (ATL)           **2**
- Los Angeles (LAX)       **3**
- New York                **6**
  - JFK
- Miami (MIA)             **8**
- Chicago O'Hare (OHD)    **4**
- Phoenix (PHX)           **7**
- Denver (DEN)            **5**
- San Franscisco (SFO)
- Washington D.C.
  - Dulles (IAD)

**I was thinking we could just narrow it down to 5-10 airports but since we have the airport IDs in the data, I don't entirely see the benefit of just picking 10 other than maybe lessening the complexity or size of the data. Maybe we could just do some groupings by U.S. region? Open to suggestions**


### 7. Airport (Arrival) / Destination

### 8. Reason For Delay
- Weather
- Carrier
- Security
- Late Aircraft
- National Aviation System (NAS)

**we can leave these split up into their own feature**

### 9. Tail Number

### 10. Elapsed Time

### 11. State

### 12. Wheels Up

### 13. Wheel Down

### 14. Taxi Time (We could create a column that sums up taxi out and taxi in. However, taxi out could be an important variable for assessing NAS delays)

# 1. Initial Load & Reconniassance 
## Questions to Answer
1. Tidy or not?
2. Entities, Attributes, Observations?
3. Variable Types?
4. Shape & scale?
5. Any obvious problems?

**I will add a table of feature names and a brief description for each so it's easy to follow the table**

### Hypothessis
- Relationships worth exploring
    - Numeric
    - Categorical
    - Numeric vs Categorical
    - Numeric vs Numeric 
    -  on-time performance vs. time of day
    -  on-time performance vs carrier
    -  on-time performance vs airport
    -  Carrier vs % of flights delayed
    -  Carrier vs departure / arrival delays

-

# Importing All Necessary Packages

In [18]:
import pandas as pd
import numpy as np
from pathlib import Path
import zipfile
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Reading In All The Source Data

In [19]:
df = pd.read_parquet("../data/bts_all.parquet")
df_aircraft = pd.read_csv("../data/Aircraft.csv")
df_airports = pd.read_csv("../data/Airports.csv")
df_airline = pd.read_csv("../data/Airline.csv")
#df_airline
df.head()

,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,...,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest
0,2022-11-23,OH,N513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,51.0,313.0,28.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN
1,2022-11-27,OH,N538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,51.0,313.0,2.0,0.0,13.0,0.0,50.0,NaN,0.0,NaN
2,2022-11-28,OH,N522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,56.0,313.0,0.0,0.0,8.0,0.0,55.0,NaN,0.0,NaN
3,2022-11-29,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,50.0,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,2022-11-30,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1819,...,NaN,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

# Initial Reconnaissance

In [20]:
df.info()
#df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 31 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          object
 1   Reporting_Airline   object
 2   Tail_Number         object
 3   Origin              object
 4   OriginCityName      object
 5   OriginStateName     object
 6   Dest                object
 7   DestCityName        object
 8   DestStateName       object
 9   CRSDepTime          int64
 10  DepDelay            float64
 11  TaxiOut             float64
 12  WheelsOff           float64
 13  WheelsOn            float64
 14  TaxiIn              float64
 15  CRSArrTime          int64
 16  ArrDelay            float64
 17  Cancelled           float64
 18  CancellationCode    object
 19  Diverted            float64
 20  ActualElapsedTime   float64
 21  AirTime             float64
 22  Distance            float64
 23  CarrierDelay        float64
 24  WeatherDelay        float64
 25  NASDelay            float64
 26  SecurityDelay       float64
 27  LateAircraftDelay   float64
 28  TotalAddGTime       float64
 29  DivAirportLandings  float64
 30  DivReachedDest      float64
dtypes: float64(19), int64(2), object(10)
memory usage: 8.2+ GB

# Updating Dtypes

In [21]:
df['FlightDate'] = pd.to_datetime(df['FlightDate'], errors="coerce") #Displaying only date for Flight Date
#df['FlightDate'] = df['FlightDate'].dt.strftime("%d/%m/%Y") #Formatting date to be in dd/mm/yyyy format

df['CRSDepTime'] = df['CRSDepTime'].astype(str).str.zfill(4) #Converting int64 to 4 digit string
df['CRSArrTime'] = df['CRSArrTime'].astype(str).str.zfill(4) #Converting int64 to 4 digit string
df['CRSDepTime'] = pd.to_datetime(df['CRSDepTime'], format="%H%M", errors='coerce') #Converting string to datetime with format proper hours and minutes format. Any invalid values will become NaT
df['CRSArrTime'] = pd.to_datetime(df['CRSArrTime'], format="%H%M", errors='coerce') #Converting string to datetime with format proper hours and minutes format. Any invalid values will become NaT
df.info()
#df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 31 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          datetime64[ns]
 1   Reporting_Airline   object
 2   Tail_Number         object
 3   Origin              object
 4   OriginCityName      object
 5   OriginStateName     object
 6   Dest                object
 7   DestCityName        object
 8   DestStateName       object
 9   CRSDepTime          datetime64[ns]
 10  DepDelay            float64
 11  TaxiOut             float64
 12  WheelsOff           float64
 13  WheelsOn            float64
 14  TaxiIn              float64
 15  CRSArrTime          datetime64[ns]
 16  ArrDelay            float64
 17  Cancelled           float64
 18  CancellationCode    object
 19  Diverted            float64
 20  ActualElapsedTime   float64
 21  AirTime             float64
 22  Distance            float64
 23  CarrierDelay        float64
 24  WeatherDelay        float64
 25  NASDelay            float64
 26  SecurityDelay       float64
 27  LateAircraftDelay   float64
 28  TotalAddGTime       float64
 29  DivAirportLandings  float64
 30  DivReachedDest      float64
dtypes: datetime64[ns](3), float64(19), object(9)
memory usage: 8.2+ GB

In [22]:
#Aircraft.csv
df['Tail_Number'] = df['Tail_Number'].str.lstrip('N') #Removing leading "N" from Tail Number (this is to be able to properly match the tail number with the correct make and model aircraft from the Aircraft.csv

df_aircraft = df_aircraft.drop(columns='MFR MDL CODE') #Dropping column, 'MFR MDL CODE' in aircraft DF

df_aircraft = df_aircraft.rename(columns= { #Changing feature names for Aircraft.csv
    'N-NUMBER': 'Tail_Number',
    'MFR': 'Manufacturer',
    'NO-SEATS': 'Number_of_Seats'
})
df = df.merge(df_aircraft, on='Tail_Number', how='left') #Merging Aircraft DF

#Airport.csv
dep_airports = df_airports.copy()
dep_airports = dep_airports.rename(columns={'lid': 'DepAirport_code',
                                          'country': 'dep_country'})
df = df.merge(dep_airports[['DepAirport_code', 'dep_country']], left_on='Origin', right_on='DepAirport_code', how='left')

dest_airports = df_airports.copy()
dest_airports = dest_airports.rename(columns={'lid': 'DestAirport_code',
                                          'country': 'dest_country'})
df = df.merge(dest_airports[['DestAirport_code', 'dest_country']], left_on='Dest', right_on='DestAirport_code', how='left')

mask = (df['dep_country'] != 'US') | (df['dest_country'] != 'US')
df.loc[mask, 'international'] = 'International'
df.loc[~mask, 'international'] = 'Domestic'
df = df.drop(columns=['DepAirport_code', 'dep_country', 'DestAirport_code', 'dest_country'])

#Airline.csv
df_airline = df_airline.rename(columns= {'OP_UNIQUE_CARRIER': 'Reporting_Airline'})
df = df.merge(df_airline, on='Reporting_Airline', how='left')
df = df.rename(columns= { 'international': 'flight_type',
                          'Description': 'Airline'})
df['Airline'] = df['Airline'].replace({
    'American Airlines Inc.': 'American Airlines',
    'Alaska Airlines Inc.': 'Alaska Airlines',
    'Delta Air Lines Inc.': 'Delta Airlines',
    'Frontier Airlines Inc.': 'Frontier Airlines',
    'Hawaiian Airlines Inc.': 'Hawaiian Airlines',
    'PSA Airlines Inc.': 'PSA Airlines',
    'Skywest Airlines Inc.': 'Skywest Airlines',
    'United Air Lines Inc.': 'United Airlines',
    'Southwest Airlines Co.': 'Southwest Airlines',
})        
df = df.drop(columns=['Reporting_Airline'])
df

,FlightDate,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,DepDelay,...,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest,Manufacturer,MODEL,Number_of_Seats,flight_type,Airline
0,2022-11-23,513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,29.0,...,0.0,0.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
1,2022-11-27,538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,52.0,...,0.0,50.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
2,2022-11-28,522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,55.0,...,0.0,55.0,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
3,2022-11-29,526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:17:00,-11.0,...,NaN,NaN,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
4,2022-11-30,526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1900-01-01 18:19:00,NaN,...,NaN,NaN,NaN,0.0,NaN,BOMBARDIER INC,CL-600-2C10,80.0,Domestic,PSA Airlines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35417935,2022-06-21,345DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,0.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Air Lines Inc.
35417936,2022-06-21,345DN,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,1900-01-01 11:07:00,18.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Air Lines Inc.
35417937,2022-06-22,117DX,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,4.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Air Lines Inc.
35417938,2022-06-22,117DX,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,1900-01-01 11:07:00,15.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Air Lines Inc.
35417939,2022-06-23,396DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,1900-01-01 13:12:00,-2.0,...,NaN,NaN,NaN,0.0,NaN,AIRBUS,A321-211,199.0,Domestic,Delta Air Lines Inc.

In [14]:
#Checking that earliest date of dataset to be January 1, 2020
earliest_flight = df['FlightDate'].min()
latest_flight = df['FlightDate'].max()
print("Earliest Flight Date:", earliest_flight.date())
print("Latest Flight Date:", latest_flight.date())

Earliest Flight Date: 2020-01-01
Latest Flight Date: 2025-07-31

In [24]:
df.columns

Index(['FlightDate', 'Tail_Number', 'Origin', 'OriginCityName',
       'OriginStateName', 'Dest', 'DestCityName', 'DestStateName',
       'CRSDepTime', 'DepDelay', 'TaxiOut', 'WheelsOff', 'WheelsOn', 'TaxiIn',
       'CRSArrTime', 'ArrDelay', 'Cancelled', 'CancellationCode', 'Diverted',
       'ActualElapsedTime', 'AirTime', 'Distance', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay',
       'TotalAddGTime', 'DivAirportLandings', 'DivReachedDest', 'Manufacturer',
       'MODEL', 'Number_of_Seats', 'flight_type', 'Airline'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 35 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          datetime64[ns]
 1   Tail_Number         object
 2   Origin              object
 3   OriginCityName      object
 4   OriginStateName     object
 5   Dest                object
 6   DestCityName        object
 7   DestStateName       object
 8   CRSDepTime          datetime64[ns]
 9   DepDelay            float64
 10  TaxiOut             float64
 11  WheelsOff           float64
 12  WheelsOn            float64
 13  TaxiIn              float64
 14  CRSArrTime          datetime64[ns]
 15  ArrDelay            float64
 16  Cancelled           float64
 17  CancellationCode    object
 18  Diverted            float64
 19  ActualElapsedTime   float64
 20  AirTime             float64
 21  Distance            float64
 22  CarrierDelay        float64
 23  WeatherDelay        float64
 24  NASDelay            float64
 25  SecurityDelay       float64
 26  LateAircraftDelay   float64
 27  TotalAddGTime       float64
 28  DivAirportLandings  float64
 29  DivReachedDest      float64
 30  Manufacturer        object
 31  MODEL               object
 32  Number_of_Seats     float64
 33  flight_type         object
 34  Airline             object
dtypes: datetime64[ns](3), float64(20), object(12)
memory usage: 9.2+ GB

In [29]:
df.describe

<bound method NDFrame.describe of          FlightDate Tail_Number Origin      OriginCityName OriginStateName  \
0        2022-11-23       513AE    DCA      Washington, DC        Virginia
1        2022-11-27       538EG    DCA      Washington, DC        Virginia
2        2022-11-28       522AE    DCA      Washington, DC        Virginia
3        2022-11-29       526EA    DCA      Washington, DC        Virginia
4        2022-11-30       526EA    DCA      Washington, DC        Virginia
...             ...         ...    ...                 ...             ...
35417935 2022-06-21       345DN    PDX        Portland, OR          Oregon
35417936 2022-06-21       345DN    SLC  Salt Lake City, UT            Utah
35417937 2022-06-22       117DX    PDX        Portland, OR          Oregon
35417938 2022-06-22       117DX    SLC  Salt Lake City, UT            Utah
35417939 2022-06-23       396DN    PDX        Portland, OR          Oregon

         Dest        DestCityName DestStateName          CRSDepTime  DepDelay  \
0         BDL        Hartford, CT   Connecticut 1900-01-01 18:17:00      29.0
1         BDL        Hartford, CT   Connecticut 1900-01-01 18:17:00      52.0
2         BDL        Hartford, CT   Connecticut 1900-01-01 18:17:00      55.0
3         BDL        Hartford, CT   Connecticut 1900-01-01 18:17:00     -11.0
4         BDL        Hartford, CT   Connecticut 1900-01-01 18:19:00       NaN
...       ...                 ...           ...                 ...       ...
35417935  SLC  Salt Lake City, UT          Utah 1900-01-01 13:12:00       0.0
35417936  PDX        Portland, OR        Oregon 1900-01-01 11:07:00      18.0
35417937  SLC  Salt Lake City, UT          Utah 1900-01-01 13:12:00       4.0
35417938  PDX        Portland, OR        Oregon 1900-01-01 11:07:00      15.0
35417939  SLC  Salt Lake City, UT          Utah 1900-01-01 13:12:00      -2.0

          ...  SecurityDelay  LateAircraftDelay  TotalAddGTime  \
0         ...            0.0                0.0            NaN
1         ...            0.0               50.0            NaN
2         ...            0.0               55.0            NaN
3         ...            NaN                NaN            NaN
4         ...            NaN                NaN            NaN
...       ...            ...                ...            ...
35417935  ...            NaN                NaN            NaN
35417936  ...            NaN                NaN            NaN
35417937  ...            NaN                NaN            NaN
35417938  ...            NaN                NaN            NaN
35417939  ...            NaN                NaN            NaN

          DivAirportLandings DivReachedDest                    Manufacturer  \
0                        0.0            NaN  BOMBARDIER INC
1                        0.0            NaN  BOMBARDIER INC
2                        0.0            NaN  BOMBARDIER INC
3                        0.0            NaN  BOMBARDIER INC
4                        0.0            NaN  BOMBARDIER INC
...                      ...            ...                             ...
35417935                 0.0            NaN  AIRBUS
35417936                 0.0            NaN  AIRBUS
35417937                 0.0            NaN  AIRBUS
35417938                 0.0            NaN  AIRBUS
35417939                 0.0            NaN  AIRBUS

                         MODEL Number_of_Seats  flight_type  \
0         CL-600-2C10                     80.0     Domestic
1         CL-600-2C10                     80.0     Domestic
2         CL-600-2C10                     80.0     Domestic
3         CL-600-2C10                     80.0     Domestic
4         CL-600-2C10                     80.0     Domestic
...                        ...             ...          ...
35417935  A321-211                       199.0     Domestic
35417936  A321-211                       199.0     Domestic
35417937  A321-211                       199.0     Domestic
35417938  A321-211                       199.0     Domestic
35417939  A321-211                       199.0     Domestic

                       Airline
0                 PSA Airlines
1                 PSA Airlines
2                 PSA Airlines
3                 PSA Airlines
4                 PSA Airlines
...                        ...
35417935  Delta Air Lines Inc.
35417936  Delta Air Lines Inc.
35417937  Delta Air Lines Inc.
35417938  Delta Air Lines Inc.
35417939  Delta Air Lines Inc.

[35417940 rows x 35 columns]>

In [28]:
df.shape

(35417940, 35)

# 2. Data Quality
- What is broken, missing, or suspicious?
- Are the dtypes correct for each variable?
- Do the values make sense?
- Where is data missing and how much?
- Are there duplicates or outliers?
- Is the data trustworthy as is?

AttributeError: 'DataFrame' object has no attribute 'dytpes'

# 3. Cleaning Decisions
- Motivation
    - How do I fix problems without corrupting the truth?
- Questions
    - Drop or fix? What's the impact on the analysis?
    - What the missingness mechanism (MCAR / MAR / MNAR)
    - Are outliers legit or are they errors?
    - What assumptions am I making?
- Hypothesis & Iteration
    - What biases might my cleaning decisions introduce
    - What sensitivity analyses should I run?
- Iteration Signals
    - Cleaning reveals new issues --> back to phase 2
    - Decisions feel arbitrary --> need domain expertise

# 4. Statistical EDA
### Content From Lecture 13a 
-Motivation

    - What patterns, relationships stories exist in the data?
-Driving Questions

    - What's "typical" for each variable?
    - How do variables relate to each other?
    - Do patterns hold across subgroups?
    What surprises emerge?

### Project

- Motivation
    -fdfsf

- Driving Questions

# 5. Transformation

# 6. Save & Document