# Introduction
### Source Data
* **United States Department of Transportation - U.S. Buerau of Transportation Statistics (Airlines, Airport, and Aviation)**
    
    URL: https://transtats.bts.gov/Fields.asp?gnoyr_VQ=FGJ

* **Federal Aviation Administration Aircraft Registration Database**
    
    URL: https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download

# Initial Questions
1. What do we want to know about airline on-time performance?
2. How will the answer be useful in decision making?

# Data Specific Questions
**1. How does on-time performance vary across carrier, airports, time, day, maybe aircraft?**
   
    -  What's the overall distribution of any flight delays? 
    -  What airline has the best and worst on-time performance? 
    -  How do routes (short/long) correlate with performance? 
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    

**2. What delay propagation patterns can we draw?**

    - Is there recovery or do they compound / propagate? 
            - Are some airlines better at recovering than others? 
        - What information can we draw from taxi times? Thinking about traffic jams at the runways due to built up delays
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What is the average total time per day in delays a carrier has? 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 

**3. What factors have the greatest effect on on-time performance**
   
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delau
        - What is the total number 

4. What is the overall cost of delays?
    -Fuel, labor, etc. 

6. What is the impact to customers?
    - Which airports should customers expect delays
    - What percent of flights are delayed 15, 30, 60+ minutes?


## Brandon Analysis Questions
    -  How do routes correlate with performance? 
    - What are the max, min, and average flight times? Is there a relationships to flight length and delays
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    - How resilient is each carrier to delay shocks?
        - What % of flights recover to on-time after a delay?
    - What is the % chance that a late arrival will cause the next flight to also be late T
    - What is the average total time per day in delays a carrier has? 
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Are taxi times leading indicators of airport congestion?
        - What is the relationship between taxi out times and departure delays (Wheels off)
    
## Trace Analysis Questions
    -  What's the overall distribution of any flight delays? 
    - What airports have the highest delays?
    -  What airline has the best and worst on-time performance? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delay?
    - What is the likelyhood of a delay based on airline, airport, and time of day?
    - What aircraft have the highest carrier delays?
    - What day of the week has the highest delays?

## Amibtion
- What is the cost to airlines due to delays? Per day? Per Year?
- 

# Key Features Needed
### 1. Date

### 2. Time of Day

### 3. Carrier
- American
- United
- Delta
- Southwest
- Alaska
- JetBlue
- Spirit
- Frontier

### 5. Airport (Departure)
- Dallas Fort-Worth (DFW) **1**
- Atlanta (ATL)           **2**
- Los Angeles (LAX)       **3**
- New York                **6**
  - JFK
- Miami (MIA)             **8**
- Chicago O'Hare (OHD)    **4**
- Phoenix (PHX)           **7**
- Denver (DEN)            **5**
- San Franscisco (SFO)
- Washington D.C.
  - Dulles (IAD)

**I was thinking we could just narrow it down to 5-10 airports but since we have the airport IDs in the data, I don't entirely see the benefit of just picking 10 other than maybe lessening the complexity or size of the data. Maybe we could just do some groupings by U.S. region? Open to suggestions**


### 7. Airport (Arrival) / Destination

### 8. Reason For Delay
- Weather
- Carrier
- Security
- Late Aircraft
- National Aviation System (NAS)

**we can leave these split up into their own feature**

### 9. Tail Number

### 10. Elapsed Time

### 11. State

### 12. Wheels Up

### 13. Wheel Down

### 14. Taxi Time (We could create a column that sums up taxi out and taxi in. However, taxi out could be an important variable for assessing NAS delays)

# 1. Initial Load & Reconniassance 
## Questions to Answer
1. Tidy or not?
2. Entities, Attributes, Observations?
3. Variable Types?
4. Shape & scale?
5. Any obvious problems?

**I will add a table of feature names and a brief description for each so it's easy to follow the table**

### Hypothessis
- Relationships worth exploring
    - Numeric
    - Categorical
    - Numeric vs Categorical
    - Numeric vs Numeric 
    -  on-time performance vs. time of day
    -  on-time performance vs carrier
    -  on-time performance vs airport
    -  Carrier vs % of flights delayed
    -  Carrier vs departure / arrival delays

-

# Importing All Necessary Packages

In [14]:
import pandas as pd
import numpy as np
from pathlib import Path
import zipfile
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Reading In All The Source Data

In [7]:
df = pd.read_parquet("../data/bts_all.parquet")
df_aircraft = pd.read_csv("../data/Aircraft.csv")
df_airports = pd.read_csv("../data/Airports.csv")
df_airline = pd.read_csv("../data/Airline.csv")
df.head()

,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,...,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest
0,2022-11-23,OH,N513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,51.0,313.0,28.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN
1,2022-11-27,OH,N538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,51.0,313.0,2.0,0.0,13.0,0.0,50.0,NaN,0.0,NaN
2,2022-11-28,OH,N522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,56.0,313.0,0.0,0.0,8.0,0.0,55.0,NaN,0.0,NaN
3,2022-11-29,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1817,...,50.0,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,2022-11-30,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,1819,...,NaN,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

# Initial Reconnaissance

In [8]:
df.info()
#df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 31 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          object
 1   Reporting_Airline   object
 2   Tail_Number         object
 3   Origin              object
 4   OriginCityName      object
 5   OriginStateName     object
 6   Dest                object
 7   DestCityName        object
 8   DestStateName       object
 9   CRSDepTime          int64
 10  DepDelay            float64
 11  TaxiOut             float64
 12  WheelsOff           float64
 13  WheelsOn            float64
 14  TaxiIn              float64
 15  CRSArrTime          int64
 16  ArrDelay            float64
 17  Cancelled           float64
 18  CancellationCode    object
 19  Diverted            float64
 20  ActualElapsedTime   float64
 21  AirTime             float64
 22  Distance            float64
 23  CarrierDelay        float64
 24  WeatherDelay        float64
 25  NASDelay            float64
 26  SecurityDelay       float64
 27  LateAircraftDelay   float64
 28  TotalAddGTime       float64
 29  DivAirportLandings  float64
 30  DivReachedDest      float64
dtypes: float64(19), int64(2), object(10)
memory usage: 8.2+ GB

# Updating Dtypes

In [9]:
df['FlightDate'] = pd.to_datetime(df['FlightDate'], errors="coerce") #Displaying only date for Flight Date
#df['FlightDate'] = df['FlightDate'].dt.strftime("%d/%m/%Y") #Formatting date to be in dd/mm/yyyy format
df['CRSDepTime'] = df['CRSDepTime'].astype(str).str.zfill(4) #Converting int64 to 4 digit string
df['CRSArrTime'] = df['CRSArrTime'].astype(str).str.zfill(4) #Converting int64 to 4 digit string
df['CRSDepTime'] = pd.to_datetime(df['CRSDepTime'], format="%H%M", errors='coerce') #Converting string to datetime with format proper hours and minutes format. Any invalid values will become NaT
df['CRSArrTime'] = pd.to_datetime(df['CRSArrTime'], format="%H%M", errors='coerce') #Converting string to datetime with format proper hours and minutes format. Any invalid values will become NaT
df.info()
#df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35417940 entries, 0 to 35417939
Data columns (total 31 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          datetime64[ns]
 1   Reporting_Airline   object
 2   Tail_Number         object
 3   Origin              object
 4   OriginCityName      object
 5   OriginStateName     object
 6   Dest                object
 7   DestCityName        object
 8   DestStateName       object
 9   CRSDepTime          datetime64[ns]
 10  DepDelay            float64
 11  TaxiOut             float64
 12  WheelsOff           float64
 13  WheelsOn            float64
 14  TaxiIn              float64
 15  CRSArrTime          datetime64[ns]
 16  ArrDelay            float64
 17  Cancelled           float64
 18  CancellationCode    object
 19  Diverted            float64
 20  ActualElapsedTime   float64
 21  AirTime             float64
 22  Distance            float64
 23  CarrierDelay        float64
 24  WeatherDelay        float64
 25  NASDelay            float64
 26  SecurityDelay       float64
 27  LateAircraftDelay   float64
 28  TotalAddGTime       float64
 29  DivAirportLandings  float64
 30  DivReachedDest      float64
dtypes: datetime64[ns](3), float64(19), object(9)
memory usage: 8.2+ GB

In [15]:
df['dep_country'] = ' '
df['dest_country'] = ' '

df_airports = df_airports.rename(columns={'lid': 'airport_code'})
df = df.merge(df_airports[['airport_code', 'country']], left_on='Origin', right_on='airport_code', how='left')
df = df.merge(df_airports[['airport_code', 'country']], left_on='Dest', right_on='airport_code', how='left')
mask = (df['dep_country'] != 'US') | (df['dest_country'] != 'US')
df.loc[mask, 'international'] = 'International'
df.loc[~mask, 'international'] = 'Domestic'
df

MergeError: Passing 'suffixes' which cause duplicate columns {'country_x', 'airport_code_x'} is not allowed.

In [68]:
#Extracting time only for departure and arrival times
df['CRSDepTime'] = df['CRSDepTime'].dt.time
df['CRSArrTime'] = df['CRSArrTime'].dt.time

#Checking that earliest date of dataset to be January 1, 2020
earliest_flight = df['FlightDate'].min()
latest_flight = df['FlightDate'].max()
print("Earliest Flight Date:", earliest.dt.date)
print("Latest Flight Date:", latest.dt.date)

#Aircraft.csv
["Tail_Number"] = ["Tail_Number"].str.lstrip("N") #Removing leading "N" from Tail Number (this is to be able to properly match the tail number with the correct make and model aircraft from the Aircraft.csv

df_aircraft = df_aircraft.drop(columns='MFR MDL CODE') #Dropping column, 'MFR MDL CODE' in aircraft DF

df_aircraft = df_aircraft.rename(columns= { #Changing feature names for Aircraft.csv
    'N-NUMBER': 'Tail_Number',
    'MFR': 'Manufacturer',
    'NO-SEATS': 'Number_of_Seats'
})
df_merged = df_mod.merge(mod_aircraft, on='Tail_Number', how='left') #Merging Aircraft DF

#Adding columns, dep_country & arr_country to main dataframe to setup for merge with Airport DF
df['dep_country'] = ' '
df['dest_country'] = ' '

#Airport.csv
df_airports = df_airports.rename(columns={'lid': 'airport_code'})
df = df.merge(airports[['airport_code', 'country']], left_on='origin', right_on='airport_code', how='left')
df = df.merge(df_airports[['airport_code', 'country']], left_on='Dest', right_on='airport_code', how='left')

mask = (df['dep_country'] != 'US') | (df['dest_country'] != 'US')
df.loc[mask, 'international'] = 'International'
df.loc[~mask, 'international'] = 'Domestic'
df

,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginStateName,Dest,DestCityName,DestStateName,CRSDepTime,...,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,TotalAddGTime,DivAirportLandings,DivReachedDest
0,2022-11-23,OH,N513AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,18:17:00,...,51.0,313.0,28.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN
1,2022-11-27,OH,N538EG,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,18:17:00,...,51.0,313.0,2.0,0.0,13.0,0.0,50.0,NaN,0.0,NaN
2,2022-11-28,OH,N522AE,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,18:17:00,...,56.0,313.0,0.0,0.0,8.0,0.0,55.0,NaN,0.0,NaN
3,2022-11-29,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,18:17:00,...,50.0,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,2022-11-30,OH,N526EA,DCA,"Washington, DC",Virginia,BDL,"Hartford, CT",Connecticut,18:19:00,...,NaN,313.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35417935,2022-06-21,DL,N345DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,13:12:00,...,90.0,630.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
35417936,2022-06-21,DL,N345DN,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,11:07:00,...,84.0,630.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
35417937,2022-06-22,DL,N117DX,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,13:12:00,...,88.0,630.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
35417938,2022-06-22,DL,N117DX,SLC,"Salt Lake City, UT",Utah,PDX,"Portland, OR",Oregon,11:07:00,...,84.0,630.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
35417939,2022-06-23,DL,N396DN,PDX,"Portland, OR",Oregon,SLC,"Salt Lake City, UT",Utah,13:12:00,...,86.0,630.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [73]:
a = df['FlightDate'].min().date()
b = df['FlightDate'].max().date()
print("Earliest Flight Date:", a)
print("Latest Flight Date:", b)

Earliest Flight Date: 2020-01-01
Latest Flight Date: 2025-07-31

In [17]:





df["Tail_Number"] = df["Tail_Number"].str.lstrip("N")

#Changing features names to be more clear
# #df = df.rename(columns={
#     '': 
  
# })

df_aircraft = df_aircraft.drop(columns='MFR MDL CODE')
#Changing feature names for Aircraft.csv
df_aircraft = df_aircraft.rename(columns= {
    'N-NUMBER': 'Tail_Number',
    'MFR': 'Manufacturer',
    'NO-SEATS': 'Number_of_Seats'
})
df_aircraft

#Changing feature names for Airport.csv
#mod_airports = df_

df_merged = df_mod.merge(mod_aircraft, on='Tail_Number', how='left')
#df_merged = df_merged.merge(

KeyError: 'TAIL_NUM'

In [18]:
df.columns
df.info()
df.describe()
df.shape()

mod_df = df.drop(columns=['', 
mod_df

# col_names = {
#     'Column Name': [
#         'FL_DATE',                 
#         'OP_CARRIER',               
#         'TAIL_NUM',            
#         'OP_CARRIER_FL_NUM',   
#         'ORIGIN',              
#         'ORIGIN_CITY_NAME',      
#         'ORIGIN_STATE_NM',       
#         'DEST',                  
#         'DEST_CITY_NAME',        
#         'DEST_STATE_NM',         
#         'DEP_TIME',              
#         'DEP_DELAY',             
#         'DEP_DELAY_NEW',         
#         'TAXI_OUT',              
#         'WHEELS_OFF',            
#         'WHEELS_ON',             
#         'TAXI_IN',               
#         'ARR_TIME',             
#         'ARR_DELAY',            
#         'ARR_DELAY_NEW',        
#         'CANCELLED',            
#         'CANCELLATION_CODE',    
#         'DIVERTED',             
#         'ACTUAL_ELAPSED_TIME',  
#         'AIR_TIME',             
#         'FLIGHTS',              
#         'DISTANCE',             
#         'DISTANCE_GROUP',      
#         'CARRIER_DELAY',        
#         'WEATHER_DELAY',        
#         'NAS_DELAY',            
#         'SECURITY_DELAY',       
#         'LATE_AIRCRAFT_DELAY',  
#         'FIRST_DEP_TIME',       
#         'TOTAL_ADD_GTIME',      
#         'LONGEST_ADD_GTIME',    
#         'DIV_AIRPORT_LANDINGS',     
#         'DIV_REACHED_DEST',         
#         'DIV_ACTUAL_ELAPSED_TIME',  
#         'DIV_ARR_DELAY',            
#         'DIV_DISTANCE', 
#     ],
#     'Description': [
#         'Flight Date',
#         'Carrier',
#         'Aircraft Tail Number',
#         'Flight Number',
#         'Origin Airport',
#         'Origin City',
#         'Origin State',
#         'Destination Airport',
#         'Destination City',
#         'Destination State',
#         'Departure Time',
#         'Scheduled Dep. Time - Actual Dep. Time',
#         'kdkdkdkd',
#         'Amount of time to taxi to for takeoff',
#         'Takeoff Time',
#         'Landing Time',
#         'Amount of time to taxi to the gate',
#         'Arrival Time',
#         'Difference in minutes between scheduled and actual arrival time',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#     ]
# }
# col_df = pd.DataFrame(col_names)
# col_df

                Column Name                                        Description
0                   FL_DATE                                        Flight Date
1                OP_CARRIER                                            Carrier
2                  TAIL_NUM                               Aircraft Tail Number
3         OP_CARRIER_FL_NUM                                      Flight Number
4                    ORIGIN                                     Origin Airport
5          ORIGIN_CITY_NAME                                        Origin City
6           ORIGIN_STATE_NM                                       Origin State
7                      DEST                                Destination Airport
8            DEST_CITY_NAME                                   Destination City
9             DEST_STATE_NM                                  Destination State
10                 DEP_TIME                                     Departure Time
11                DEP_DELAY             Scheduled Dep. Time - Actual Dep. Time
12            DEP_DELAY_NEW                                           kdkdkdkd
13                 TAXI_OUT              Amount of time to taxi to for takeoff
14               WHEELS_OFF                                       Takeoff Time
15                WHEELS_ON                                       Landing Time
16                  TAXI_IN                 Amount of time to taxi to the gate
17                 ARR_TIME                                       Arrival Time
18                ARR_DELAY  Difference in minutes between scheduled and ac...
19            ARR_DELAY_NEW                                           jndcjdnc
20                CANCELLED                                           jndcjdnc
21        CANCELLATION_CODE                                           jndcjdnc
22                 DIVERTED                                           jndcjdnc
23      ACTUAL_ELAPSED_TIME                                           jndcjdnc
24                 AIR_TIME                                           jndcjdnc
25                  FLIGHTS                                           jndcjdnc
26                 DISTANCE                                           jndcjdnc
27           DISTANCE_GROUP                                           jndcjdnc
28            CARRIER_DELAY                                           jndcjdnc
29            WEATHER_DELAY                                           jndcjdnc
30                NAS_DELAY                                           jndcjdnc
31           SECURITY_DELAY                                           jndcjdnc
32      LATE_AIRCRAFT_DELAY                                           jndcjdnc
33           FIRST_DEP_TIME                                           jndcjdnc
34          TOTAL_ADD_GTIME                                           jndcjdnc
35        LONGEST_ADD_GTIME                                           jndcjdnc
36     DIV_AIRPORT_LANDINGS                                           jndcjdnc
37         DIV_REACHED_DEST                                           jndcjdnc
38  DIV_ACTUAL_ELAPSED_TIME                                           jndcjdnc
39            DIV_ARR_DELAY                                           jndcjdnc
40             DIV_DISTANCE                                           jndcjdnc

In [3]:
#Changing features names to be more clear
mod_df = df.rename(columns={
    'FL_DATE': 'Flight Date',
    'OP_CARRIER': 'Carrier',
    'TAIL_NUM': 'Tail Number',
    'OP_CARRIER_FL_NUM': 'Flight Number',
    'ORIGIN': 'Origin Airport',
    'ORIGIN_CITY_NAME': 'Origin City',
    'ORIGIN_STATE_NM': 'Origin State',
    'DEST': 'Destination Airport',
    'DEST_CITY_NAME': 'Destination City',
    'DEST_STATE_NM': 'Destination State'
    
})

mod_df = df.drop(['Fight Number', 
mod_df

col_names = {
    'Column Name': [
        'FL_DATE',                 
        'OP_CARRIER',               
        'TAIL_NUM',            
        'OP_CARRIER_FL_NUM',   
        'ORIGIN',              
        'ORIGIN_CITY_NAME',      
        'ORIGIN_STATE_NM',       
        'DEST',                  
        'DEST_CITY_NAME',        
        'DEST_STATE_NM',         
        'DEP_TIME',              
        'DEP_DELAY',             
        'DEP_DELAY_NEW',         
        'TAXI_OUT',              
        'WHEELS_OFF',            
        'WHEELS_ON',             
        'TAXI_IN',               
        'ARR_TIME',             
        'ARR_DELAY',            
        'ARR_DELAY_NEW',        
        'CANCELLED',            
        'CANCELLATION_CODE',    
        'DIVERTED',             
        'ACTUAL_ELAPSED_TIME',  
        'AIR_TIME',             
        'FLIGHTS',              
        'DISTANCE',             
        'DISTANCE_GROUP',      
        'CARRIER_DELAY',        
        'WEATHER_DELAY',        
        'NAS_DELAY',            
        'SECURITY_DELAY',       
        'LATE_AIRCRAFT_DELAY',  
        'FIRST_DEP_TIME',       
        'TOTAL_ADD_GTIME',      
        'LONGEST_ADD_GTIME',    
        'DIV_AIRPORT_LANDINGS',     
        'DIV_REACHED_DEST',         
        'DIV_ACTUAL_ELAPSED_TIME',  
        'DIV_ARR_DELAY',            
        'DIV_DISTANCE', 
    ],
    'Description': [
        'Flight Date',
        'Carrier',
        'Aircraft Tail Number',
        'Flight Number',
        'Origin Airport',
        'Origin City',
        'Origin State',
        'Destination Airport',
        'Destination City',
        'Destination State',
        'Departure Time',
        'Scheduled Dep. Time - Actual Dep. Time',
        'kdkdkdkd',
        'Amount of time to taxi to for takeoff',
        'Takeoff Time',
        'Landing Time',
        'Amount of time to taxi to the gate',
        'Arrival Time',
        'Difference in minutes between scheduled and actual arrival time',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
    ]
}
col_df = pd.DataFrame(col_names)
col_df

,Flight Date,Carrier,Tail Number,Flight Number,Origin Airport,Origin City,Origin State,Destination Airport,Destination City,Destination State,...,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE
0,2025-01-01,AA,N101NN,164,SFO,"San Francisco, CA",California,JFK,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,2025-01-01,AA,N101NN,76,JFK,"New York, NY",New York,SFO,"San Francisco, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,2025-01-01,AA,N102UW,3244,SAT,"San Antonio, TX",Texas,CLT,"Charlotte, NC",North Carolina,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,2025-01-01,AA,N103NN,185,JFK,"New York, NY",New York,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
4,2025-01-01,AA,N103NN,2455,BOS,"Boston, MA",Massachusetts,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025-01-31,YX,N979RP,4513,LGA,"New York, NY",New York,CLE,"Cleveland, OH",Ohio,...,0.0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539743,2025-01-31,YX,N979RP,4654,LGA,"New York, NY",New York,SDF,"Louisville, KY",Kentucky,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539744,2025-01-31,YX,N979RP,4654,SDF,"Louisville, KY",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539745,2025-01-31,YX,N979RP,4666,CVG,"Cincinnati, OH",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539746,2025-01-31,YX,N979RP,4787,LGA,"New York, NY",New York,GSP,"Greer, SC",South Carolina,...,0.0,29.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

# 2. Data Quality
- What is broken, missing, or suspicious?
- Are the dtypes correct for each variable?
- Do the values make sense?
- Where is data missing and how much?
- Are there duplicates or outliers?
- Is the data trustworthy as is?

AttributeError: 'DataFrame' object has no attribute 'dytpes'

# 3. Cleaning Decisions
- Motivation
    - How do I fix problems without corrupting the truth?
- Questions
    - Drop or fix? What's the impact on the analysis?
    - What the missingness mechanism (MCAR / MAR / MNAR)
    - Are outliers legit or are they errors?
    - What assumptions am I making?
- Hypothesis & Iteration
    - What biases might my cleaning decisions introduce
    - What sensitivity analyses should I run?
- Iteration Signals
    - Cleaning reveals new issues --> back to phase 2
    - Decisions feel arbitrary --> need domain expertise

# 4. Statistical EDA
### Content From Lecture 13a 
-Motivation

    - What patterns, relationships stories exist in the data?
-Driving Questions

    - What's "typical" for each variable?
    - How do variables relate to each other?
    - Do patterns hold across subgroups?
    What surprises emerge?

### Project

- Motivation
    -fdfsf

- Driving Questions

# 5. Transformation

# 6. Save & Document