## Introduction

In [7]:
import pandas as pd
from pathlib import Path

## Phase 1: Initial Reconnaisance
Seeks to answer the following questions:
- Tidy or not?
- What are the entities, attributes (cols), observations (rows)?
- What variable types do I have?
- What's the rough shape and scale?
- Are there obvious problems?

In [19]:
#load arrivals datset
arrivals_path = Path("../data/Raw/Arrivals_AA_DFW_2016_2025.csv")
arrivals = pd.read_csv(arrivals_path, skiprows=7,parse_dates=["Date (MM/DD/YYYY)"])

arrivals.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,AA,2016-01-01,5.0,N439AA,OKC,09:35,09:32,66.0,65.0,-3.0,09:17,15.0,0.0,0.0,0.0,0.0,0.0
1,AA,2016-01-01,6.0,N367AA,OGG,05:07,04:28,427.0,388.0,-39.0,04:24,4.0,0.0,0.0,0.0,0.0,0.0
2,AA,2016-01-01,8.0,N383AA,HNL,06:03,05:18,443.0,405.0,-45.0,05:14,4.0,0.0,0.0,0.0,0.0,0.0
3,AA,2016-01-01,25.0,N3KYAA,PHL,20:44,20:40,239.0,236.0,-4.0,20:34,6.0,0.0,0.0,0.0,0.0,0.0
4,AA,2016-01-01,36.0,N881AA,SFO,13:51,13:28,211.0,191.0,-23.0,13:21,7.0,0.0,0.0,0.0,0.0,0.0

In [20]:
#load departures datset
departures_path = Path("../data/Raw/Departures_AA_DFW_2016_2025.csv")
departures = pd.read_csv(departures_path, skiprows=7,parse_dates=["Date (MM/DD/YYYY)"])

departures.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,AA,2016-01-01,5.0,N361AA,HNL,12:25,14:26,516.0,529.0,121.0,14:45,19.0,121.0,0.0,13.0,0.0,0.0
1,AA,2016-01-01,7.0,N367AA,OGG,09:05,09:06,509.0,512.0,1.0,09:29,23.0,0.0,0.0,0.0,0.0,0.0
2,AA,2016-01-01,25.0,N3KYAA,PHL,12:50,12:43,185.0,161.0,-7.0,12:55,12.0,0.0,0.0,0.0,0.0,0.0
3,AA,2016-01-01,37.0,N879AA,SFO,18:45,19:04,237.0,259.0,19.0,19:22,18.0,19.0,0.0,22.0,0.0,0.0
4,AA,2016-01-01,43.0,N4YEAA,DTW,10:45,10:41,158.0,157.0,-4.0,11:04,23.0,0.0,0.0,0.0,0.0,0.0

In [26]:
#Ensure we only have "AA" as the carrier
print("Arrivals Carrier Codes:",arrivals["Carrier Code"].value_counts())
print("Departures Cardrier Codes:", departures["Carrier Code"].value_counts())

Arrivals Carrier Codes: Carrier Code
AA                                              1382405
 SOURCE: Bureau of Transportation Statistics          1
Name: count, dtype: int64
Departures Cardrier Codes: Carrier Code
AA                                              1382469
 SOURCE: Bureau of Transportation Statistics          1
Name: count, dtype: int64

In [44]:
#Drop Carrier Code and Tail Number Columns
departures.drop(columns=["Carrier Code", "Tail Number"],inplace=True)
arrivals.drop(columns=["Carrier Code", "Tail Number"],inplace=True)

In [45]:
arrivals.head()

,Date (MM/DD/YYYY),Flight Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,2016-01-01,5.0,OKC,09:35,09:32,66.0,65.0,-3.0,09:17,15.0,0.0,0.0,0.0,0.0,0.0
1,2016-01-01,6.0,OGG,05:07,04:28,427.0,388.0,-39.0,04:24,4.0,0.0,0.0,0.0,0.0,0.0
2,2016-01-01,8.0,HNL,06:03,05:18,443.0,405.0,-45.0,05:14,4.0,0.0,0.0,0.0,0.0,0.0
3,2016-01-01,25.0,PHL,20:44,20:40,239.0,236.0,-4.0,20:34,6.0,0.0,0.0,0.0,0.0,0.0
4,2016-01-01,36.0,SFO,13:51,13:28,211.0,191.0,-23.0,13:21,7.0,0.0,0.0,0.0,0.0,0.0

Tidiness:  This dataset is fairly tidy.  The delay causes columns (delay carrier, weaqther, etc.) could be merged into a single "Cause" column with each type as an obver

In [22]:
# Missing Data per column
arrivals.isna().sum()

Carrier Code                                   0
Date (MM/DD/YYYY)                              1
Flight Number                                  1
Tail Number                                 2213
Origin Airport                                 1
Scheduled Arrival Time                         1
Actual Arrival Time                            1
Scheduled Elapsed Time (Minutes)               1
Actual Elapsed Time (Minutes)                  1
Arrival Delay (Minutes)                        1
Wheels-on Time                                 1
Taxi-In time (Minutes)                         1
Delay Carrier (Minutes)                        1
Delay Weather (Minutes)                        1
Delay National Aviation System (Minutes)       1
Delay Security (Minutes)                       1
Delay Late Aircraft Arrival (Minutes)          1
dtype: int64

In [33]:
# Attributes
print("Arrivals Info")
arrivals.info()
print("="*20)
print()
print("Departures Info")
departures.info()

Arrivals Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382406 entries, 0 to 1382405
Data columns (total 17 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Carrier Code                              1382406 non-null  object
 1   Date (MM/DD/YYYY)                         1382405 non-null  datetime64[ns]
 2   Flight Number                             1382405 non-null  float64
 3   Tail Number                               1380193 non-null  object
 4   Origin Airport                            1382405 non-null  object
 5   Scheduled Arrival Time                    1382405 non-null  object
 6   Actual Arrival Time                       1382405 non-null  object
 7   Scheduled Elapsed Time (Minutes)          1382405 non-null  float64
 8   Actual Elapsed Time (Minutes)             1382405 non-null  float64
 9   Arrival Delay (Minutes)                   1382405 non-null  float64
 10  Wheels-on Time                            1382405 non-null  object
 11  Taxi-In time (Minutes)                    1382405 non-null  float64
 12  Delay Carrier (Minutes)                   1382405 non-null  float64
 13  Delay Weather (Minutes)                   1382405 non-null  float64
 14  Delay National Aviation System (Minutes)  1382405 non-null  float64
 15  Delay Security (Minutes)                  1382405 non-null  float64
 16  Delay Late Aircraft Arrival (Minutes)     1382405 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(6)
memory usage: 179.3+ MB
====================

Departures Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382470 entries, 0 to 1382469
Data columns (total 17 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Carrier Code                              1382470 non-null  object
 1   Date (MM/DD/YYYY)                         1382469 non-null  datetime64[ns]
 2   Flight Number                             1382469 non-null  float64
 3   Tail Number                               1380181 non-null  object
 4   Destination Airport                       1382469 non-null  object
 5   Scheduled departure time                  1382469 non-null  object
 6   Actual departure time                     1382469 non-null  object
 7   Scheduled elapsed time (Minutes)          1382469 non-null  float64
 8   Actual elapsed time (Minutes)             1382469 non-null  float64
 9   Departure delay (Minutes)                 1382469 non-null  float64
 10  Wheels-off time                           1382469 non-null  object
 11  Taxi-Out time (Minutes)                   1382469 non-null  float64
 12  Delay Carrier (Minutes)                   1382469 non-null  float64
 13  Delay Weather (Minutes)                   1382469 non-null  float64
 14  Delay National Aviation System (Minutes)  1382469 non-null  float64
 15  Delay Security (Minutes)                  1382469 non-null  float64
 16  Delay Late Aircraft Arrival (Minutes)     1382469 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(6)
memory usage: 179.3+ MB